<div id="skipNavJCSDA"><a href="#skipTarget">Skip Top Navigation</a></div>
<div class="clearing"></div>
<table id="mainTable" cellpadding="0" cellspacing="0" border="0"
	summary="this table is for page layout purposes only, not tabular data">
  <tr id="printBanner">
    <td colspan="2">
		<img src="images/banner/CRTM_banner_print.jpg" 
		alt="only rendered in printing; banner for Community Radiative Transfer Model (CRTM)" /></td>
	</tr>
  <tr>
		<td colspan="2"><div id="topBanner"><a 
			href="index.php" title="link to CRTM home page"><img 
    	src="images/banner/CRTM_banner_wide2.jpg" alt="CRTM Logo and banner" 
	    /></a></div></td>
  </tr>
