	<tr>
		<td colspan="2">
			<div id="bottomBanner">
				<div class="left">
				<?php
				$unixts = getlastmod(); //last modified date/time for this web page as Unix timestamp
				echo "Updated " . date ("F j, Y g:m A",$unixts); //ex: January 15, 2004 10 AM 
				echo "<br />";
				// echo "http://www.orbit.nesdis.noaa.gov" . $_SERVER['PHP_SELF'];
				// echo "<br />";
				?>
				<a href="http://www.noaa.gov/"><acronym
					title="National Oceanographic and Atmospheric Administration">NOAA</acronym></a>&nbsp;|&nbsp;<a 
					href="http://www.nws.noaa.gov/"><acronym 
					title="National Weather Service">NWS</acronym></a>&nbsp;|&nbsp;<a 
					href="http://www.nasa.gov/"><acronym
					title="National Aeronautics and Space Administration">NASA</acronym></a><br /><a 
					href="http://www.nrlmry.navy.mil/"
					title="Naval Research Laboratory - Marine Meteorology Division">Navy Weather</a>&nbsp;|&nbsp;<a 
					href="http://www.afweather.af.mil/"
					title="Air Force Weather">Air Force Weather</a><img src="images/1pix.gif" 
					alt="" /></div>

        <div class="right"><a href="http://www.noaa.gov/privacy.html">Privacy</a>&nbsp;|&nbsp;<a 
					href="http://www.jcsda.noaa.gov/productdisclaimer.php">Link&nbsp;&amp;&nbsp;Product&nbsp;Disclaimers</a>&nbsp;|&nbsp;<a 
					href="http://www.cio.noaa.gov/itmanagement/infoq.htm">Information&nbsp;Quality</a><img src="images/1pix.gif" 
					alt="" /><br />
					<a href="http://www.jcsda.noaa.gov/accessibility.php">Accessibility</a>&nbsp;|&nbsp;<a href="mailto:Paul.Vandelst@noaa.gov">CRTM webmaster</a><br />
					Hosted for JCSDA at <a href="http://www.orbit.nesdis.noaa.gov/star/index.php"><acronym 
					title="Center for Satellite Applications and Research">STAR</acronym></a></div>
				<div class="rightImages"><a 
					href="http://www.w3.org/WAI/WCAG1A-Conformance"
      		title="Explanation of Level A Conformance"><img 
      		src="http://www.w3.org/WAI/wcag1A.gif"
          alt="Level A conformance icon, W3C-WAI Web Content Accessibility Guidelines 1.0" 
          /></a><a href="http://validator.w3.org/check?uri=referer"
      		title="This page validates as HTML 4.01 Transitional."><img 
      		src="http://www.w3.org/Icons/valid-html401"
          alt="icon for valid HTML 4.01 coding" 
          /></a></div>
				<div class="clearing"></div>
			</div>
			<script language="JavaScript" src="js/menuControllerPHP.js" type="text/javascript"></script>
		</td>
  </tr>



