			<div class="leftNav">
				<ul>
					<li id="JCSDAindex"><a 
					href="JCSDAindex.php">JCSDA Home</a></li>
				</ul>
				<ul>
					<li id="index"><a href="index.php">CRTM Home</a>
						<ul class="detailContainer">
							<li id="background"><a 
								href="background.php">Program Background</a></li>
							<li id="team"><a
								href="team.php">Team Members</a></li>
							<li id="workinggroup"><a 
								href="workinggroup.php">CRTM Working Group</a></li>
							<li id="contact"><a 
								href="contact.php">Contact</a></li>
							<li id="relatedlinks"><a 
								href="relatedlinks.php">Related Links</a></li>
						</ul>
					</li>
				</ul>
				<ul>
					<li id="quickstartguide"><a 
					href="quickstartguide.php">Quick Start Guide</a></li>
				</ul>
				<ul>
					<li id="description"><a 
					href="description.php">Description</a>
						<ul class="detailContainer">
							<li id="overview"><a 
								href="overview.php">Overview</a></li>
							<li id="conventions"><a
								href="conventions.php">Conventions</a></li>
							<li id="userinterface"><a 
								href="userinterface.php">User Interface</a></li>
							<li id="devInterface"><a 
								href="devInterface.php">Developer Interface</a></li>
							<li id="coeffData"><a 
								href="coeffData.php">Coefficient Data</a></li>
							<li id="testData"><a 
								href="testData.php">Test Data</a></li>
						</ul>
					</li>
				</ul>
				<ul>
					<li id="documents"><a 
					href="documents.php">Documents</a></li>
				</ul>
				<ul>
					<li id="publications"><a 
					href="publications.php">Publications</a></li>
				</ul>
				<ul>
					<li id="downloads"><a 
					href="downloads.php">Downloads</a></li>
				</ul>

		</div><!-- end of navlist -->

			<div class="searchBox">
			<form 
				method="get" action="http://usasearch.gov/search">
				<input type="hidden" name="affiliate" value="orbit.nesdis.noaa.gov_jcsda" />
		    <input type="hidden" name="v:project" value="firstgov" />
		  	<input 
		  	value="Enter search term(s)"
		  	title="text field for search input"
				onfocus="if(this.value=='Enter search term(s)')this.value='';"
		  	type="text" name="query" id="query-field"> <input 
		  	type="submit" value="Go" title="execute search" id="Go" /><br />
				<input type="radio" id="JCSDA" name="affiliate" checked="checked"
		  	value="orbit.nesdis.noaa.gov_jcsda"
		  	title="radio button to set search scope to JCSDA site only"><label for="JCSDA">This site only</label><br /><input 
		  	type="radio" id="NOAA" name="affiliate" value="noaa.gov"
		  	title="radio button to set search scope to all of NOAA's websites"><label 
		  	for="NOAA">All of NOAA</label>
		  	<p><a 
		  	href="http://usasearch.gov/search?v:project=firstgov&amp;form=advanced-firstgov&amp;v:frame=form&amp;affiliate=orbit.nesdis.noaa.gov_jcsda">advanced search</a></p></form>
			</div>
		