<div class="leftNav">
  <ul>
    <li id="JCSDAindex"><a href="JCSDAindex.php">JCSDA Home</a></li>
  </ul>

  <ul>
    <li id="index"><a href="index.php">CRTM Home</a>
    <ul class="detailContainer">
      <li id="idx_conventions"><a href="idx_conventions.php">Conventions</a></li>
      <li id="idx_quickstartguide"><a href="idx_quickstartguide.php">Quick Start Guide</a></li>
    </ul>
    </li>
  </ul>

  <ul>
    <li id="userinterface"><a href="userinterface.php">User Interface</a>
    <ul class="detailContainer">
      <li id="ui_publicstructures"><a href="ui_publicstructures.php">Public Structures</a>
        <ul>
          <li id="ui_ps_atmosphere"><a href="ui_ps_atmosphere.php">Atmosphere</a></li>
          <li id="ui_ps_channelinfo"><a href="ui_ps_channelinfo.php">ChannelInfo</a></li>
          <li id="ui_ps_geometryinfo"><a href="ui_ps_geometryinfo.php">GeometryInfo</a></li>
          <li id="ui_ps_options"><a href="ui_ps_options.php">Options</a></li>
          <li id="ui_ps_rtsolution"><a href="ui_ps_rtsolution.php">RTSolution</a></li>
          <li id="ui_ps_surface"><a href="ui_ps_surface.php">Surface</a></li>
        </ul>
      </li>
      <li id="ui_initialization"><a href="ui_initialization.php">Initialization</a></li>
      <li id="ui_components"><a href="ui_components.php">Components</a>
        <ul>
          <li id="ui_cmp_forward"><a href="ui_cmp_forward.php">Forward Model</a></li>
          <li id="ui_cmp_tangentlinear"><a href="ui_cmp_tangentlinear.php">Tangent-Linear Model</a></li>
          <li id="ui_cmp_adjoint"><a href="ui_cmp_adjoint.php">Adjoint Model</a></li>
          <li id="ui_cmp_kmatrix"><a href="ui_cmp_kmatrix.php">K-Matrix Model</a></li>
        </ul>
      </li>
      <li id="ui_destruction"><a href="ui_destruction.php">Destruction</a></li>
    </ul>
    </li>
  </ul>

  <ul>
    <li id="developerinterface"><a href="developerinterface.php">Developer Interface</a>
    <ul class="detailContainer">
      <li id="di_AtmAbsorption"><a href="di_AtmAbsorption.php">AtmAbsorption</a></li>
      <li id="di_AtmScatter"><a href="di_AtmScatter.php">AtmScatter</a></li>
      <li id="di_SfcOptics"><a href="di_SfcOptics.php">SfcOptics</a></li>
      <li id="di_RTSolution"><a href="di_RTSolution.php">RTSolution</a></li>
    </ul>
    </li>
  </ul>

  <ul>
    <li id="shareddata"><a href="shareddata.php">Shared Data</a>
    <ul class="detailContainer">
      <li id="sd_SpcCoeff"><a href="sd_SpcCoeff.php">SpcCoeff</a></li>
      <li id="sd_TauCoeff"><a href="sd_TauCoeff.php">TauCoeff</a></li>
      <li id="sd_EmisCoeff"><a href="sd_EmisCoeff.php">EmisCoeff</a></li>
      <li id="sd_CloudCoeff"><a href="sd_CloudCoeff.php">CloudCoeff</a></li>
      <li id="sd_AerosolCoeff"><a href="sd_AerosolCoeff.php">AerosolCoeff</a></li>
    </ul>
    </li>
  </ul>

  <ul>
    <li id="testdata"><a href="testdata.php">Test Data</a></li>
  </ul>

  <ul>
    <li id="program"><a href="program.php">CRTM program</a>
    <ul class="detailContainer">
      <li id="pgm_background"><a href="pgm_background.php">Background</a></li>
      <li id="pgm_team"><a href="pgm_team.php">Team Members</a></li>
      <li id="pgm_workinggroup"><a href="pgm_workinggroup.php">CRTM Working Group</a></li>
      <li id="pgm_contact"><a href="pgm_contact.php">Contact</a></li>
      <li id="pgm_relatedlinks"><a href="pgm_relatedlinks.php">Related Links</a></li>
    </ul>
    </li>
  </ul>
  
  <ul>
    <li id="documents"><a href="documents.php">Documents</a></li>
  </ul>

  <ul>
    <li id="publications"><a href="publications.php">Publications</a></li>
  </ul>

  <ul>
    <li id="downloads"><a href="downloads.php">Downloads</a></li>
  </ul>

</div><!-- end of navlist -->

<div class="searchBox">
  <form method="get" action="http://usasearch.gov/search">
    <input type="hidden" name="affiliate" value="orbit.nesdis.noaa.gov_jcsda" />
    <input type="hidden" name="v:project" value="firstgov" />
    <input value="Enter search term(s)" title="text field for search input" onfocus="if(this.value=='Enter search term(s)')this.value='';" type="text" name="query" id="query-field">
    <input type="submit" value="Go" title="execute search" id="Go" /><br />
    <input type="radio" id="JCSDA" name="affiliate" checked="checked" value="orbit.nesdis.noaa.gov_jcsda" title="radio button to set search scope to JCSDA site only">
    <label for="JCSDA">This site only</label><br />
    <input type="radio" id="NOAA" name="affiliate" value="noaa.gov" title="radio button to set search scope to all of NOAA's websites">
    <label for="NOAA">All of NOAA</label>
    <p><a href="http://usasearch.gov/search?v:project=firstgov&amp;form=advanced-firstgov&amp;v:frame=form&amp;affiliate=orbit.nesdis.noaa.gov_jcsda">advanced search</a></p>
  </form>
</div>
		
