#==============================================================================
#
# Makefile for RTM statistics generation program
#
#==============================================================================

#-----------------------------------------------------------------------------
#                          -- Define macros --
#-----------------------------------------------------------------------------

include make.macros


# -------------
# This makefile
# -------------

MAKE_FILE = makefile


# ---------------
# Executable file
# ---------------

EXE_FILE = Generate_Profile_Set_Stats


# ------------
# Object files
# ------------

UTILITY_OBJ_FILES = type_kinds.o \
                    file_utility.o \
                    error_handler.o \
                    Compare_Float_Numbers.o \
                    Coeff_Binary_Utility.o \
                    List_File_Utility.o
NETCDF_OBJ_FILES = netCDF_Utility.o \
                   netCDF_Dimension_Utility.o \
                   netCDF_Variable_Utility.o \
                   netCDF_Attribute_Utility.o
SENSORINFO_OBJ_FILES = SensorInfo_Define.o \
                       SensorInfo_LinkedList.o \
                       SensorInfo_IO.o
ATMPROFILE_OBJ_FILES = AtmProfile_Define.o \
                       AtmProfile_netCDF_IO.o
SPCCOEFF_OBJ_FILES = SpcCoeff_Define.o \
                     SpcCoeff_Binary_IO.o
TAUCOEFF_OBJ_FILES = TauCoeff_Define.o \
                     TauCoeff_Binary_IO.o
TAUPROFILE_OBJ_FILES = TauProfile_Define.o \
                       TauProfile_netCDF_IO.o
RTMARG_OBJ_FILES = RTMarg_Define.o
RTMSTATS_OBJ_FILES = RTMstats_Define.o \
                     RTMstats_netCDF_IO.o
NCEP_RTM_OBJ_FILES = parameters.o \
                     sensor_planck_routines.o \
                     spectral_coefficients.o \
                     transmittance_coefficients.o \
                     initialize.o \
                     absorber_profile.o \
                     predictors.o \
                     transmittance.o \
                     radiance.o \
                     forward_model.o

OBJ_FILES = $(UTILITY_OBJ_FILES) \
            $(NETCDF_OBJ_FILES) \
            $(SENSORINFO_OBJ_FILES) \
            $(ATMPROFILE_OBJ_FILES) \
            $(SPCCOEFF_OBJ_FILES) \
            $(TAUCOEFF_OBJ_FILES) \
            $(TAUPROFILE_OBJ_FILES) \
            $(RTMARG_OBJ_FILES) \
            $(RTMSTATS_OBJ_FILES) \
            $(NCEP_RTM_OBJ_FILES) \
            $(EXE_FILE).o



# -------------------------------
# Include and library definitions
# -------------------------------

INCLUDES = -I$(HOME)/local/netcdf/include
LIBRARIES = -L$(HOME)/local/netcdf/lib -lnetcdf



#-----------------------------------------------------------------------------
#                          -- Define dependecies --
#-----------------------------------------------------------------------------

# ---------------------
# Make based on OS type
# ---------------------

all:
	@echo "OS type detected: "`uname -s`
	@case `uname -s` in \
	  "SunOS")   make -f $(MAKE_FILE) the_program $(SUNOS_FLAGS) ;; \
	  "AIX")     make -f $(MAKE_FILE) the_program $(AIX_FLAGS) ;; \
	  "IRIX64" ) make -f $(MAKE_FILE) the_program $(IRIX64_FLAGS) ;; \
	  "Linux" )  make -f $(MAKE_FILE) the_program $(Linux_FLAGS) ;; \
	  *) echo "This system is not supported" ;; \
	esac



# ----------------
# Make the program
# ----------------

the_program: $(OBJ_FILES)
	$(FL) $(OBJ_FILES) $(EXTRA_FL_FLAGS) $(FL_FLAGS) $(EXE_FILE)



# --------
# Clean up
# --------

clean:
	$(REMOVE) $(OBJ_FILES) $(EXE_FILE) *.mod *.MOD *.stb


# ----------
# Install it
# ----------

install:
	@if [ -d $(HOME)/bin ]; then \
	    $(MOVE) $(EXE_FILE) $(HOME)/bin; \
	fi


# ---------------
# Dependency list
# ---------------

type_kinds.o : type_kinds.f90 
file_utility.o : file_utility.f90 
error_handler.o : error_handler.f90 file_utility.o 
Compare_Float_Numbers.o : Compare_Float_Numbers.f90 type_kinds.o 
Coeff_Binary_Utility.o : Coeff_Binary_Utility.f90 type_kinds.o file_utility.o error_handler.o 
List_File_Utility.o : List_File_Utility.f90 type_kinds.o file_utility.o error_handler.o 

netCDF_Variable_Utility.o : netCDF_Variable_Utility.f90 type_kinds.o error_handler.o 
netCDF_Dimension_Utility.o : netCDF_Dimension_Utility.f90 type_kinds.o error_handler.o 
netCDF_Attribute_Utility.o : netCDF_Attribute_Utility.f90 type_kinds.o error_handler.o 
netCDF_Utility.o : netCDF_Utility.f90 type_kinds.o error_handler.o netCDF_Dimension_Utility.o netCDF_Variable_Utility.o netCDF_Attribute_Utility.o 

parameters.o : parameters.f90 type_kinds.o 
sensor_planck_routines.o : sensor_planck_routines.f90 type_kinds.o parameters.o spectral_coefficients.o 
spectral_coefficients.o : spectral_coefficients.f90 type_kinds.o error_handler.o parameters.o SpcCoeff_Define.o SpcCoeff_Binary_IO.o 
transmittance_coefficients.o : transmittance_coefficients.f90 type_kinds.o error_handler.o parameters.o TauCoeff_Define.o TauCoeff_Binary_IO.o 
initialize.o : initialize.f90 error_handler.o transmittance_coefficients.o spectral_coefficients.o 
absorber_profile.o : absorber_profile.f90 type_kinds.o parameters.o 
predictors.o : predictors.f90 type_kinds.o parameters.o error_handler.o 
transmittance.o : transmittance.f90 type_kinds.o parameters.o transmittance_coefficients.o 
radiance.o : radiance.f90 type_kinds.o parameters.o spectral_coefficients.o sensor_planck_routines.o 
forward_model.o : forward_model.f90 type_kinds.o error_handler.o parameters.o spectral_coefficients.o absorber_profile.o predictors.o transmittance.o radiance.o 

SensorInfo_LinkedList.o : SensorInfo_LinkedList.f90 type_kinds.o error_handler.o SensorInfo_Define.o 
SensorInfo_IO.o : SensorInfo_IO.f90 type_kinds.o file_utility.o error_handler.o SensorInfo_Define.o SensorInfo_LinkedList.o 
SensorInfo_Define.o : SensorInfo_Define.f90 type_kinds.o error_handler.o 

AtmProfile_Define.o : AtmProfile_Define.f90 type_kinds.o error_handler.o 
AtmProfile_netCDF_IO.o : AtmProfile_netCDF_IO.f90 type_kinds.o error_handler.o AtmProfile_Define.o netCDF_Utility.o 

TauProfile_netCDF_IO.o : TauProfile_netCDF_IO.f90 type_kinds.o error_handler.o TauProfile_Define.o netCDF_Utility.o 
TauProfile_Define.o : TauProfile_Define.f90 type_kinds.o error_handler.o Compare_Float_Numbers.o 

SpcCoeff_Define.o : SpcCoeff_Define.f90 type_kinds.o error_handler.o Compare_Float_Numbers.o 
SpcCoeff_Binary_IO.o : SpcCoeff_Binary_IO.f90 type_kinds.o file_utility.o error_handler.o SpcCoeff_Define.o Coeff_Binary_Utility.o 

TauCoeff_Define.o : TauCoeff_Define.f90 type_kinds.o error_handler.o Compare_Float_Numbers.o 
TauCoeff_Binary_IO.o : TauCoeff_Binary_IO.f90 type_kinds.o file_utility.o error_handler.o TauCoeff_Define.o Coeff_Binary_Utility.o 

RTMarg_Define.o : RTMarg_Define.f90 type_kinds.o error_handler.o 

RTMstats_Define.o : RTMstats_Define.f90 type_kinds.o error_handler.o 
RTMstats_netCDF_IO.o : RTMstats_netCDF_IO.f90 type_kinds.o error_handler.o RTMstats_Define.o netCDF_Utility.o 

$(EXE_FILE).o : $(EXE_FILE).f90 type_kinds.o file_utility.o error_handler.o List_File_Utility.o AtmProfile_Define.o AtmProfile_netCDF_IO.o SensorInfo_Define.o SensorInfo_LinkedList.o SensorInfo_IO.o TauProfile_Define.o TauProfile_netCDF_IO.o RTMarg_Define.o RTMstats_Define.o RTMstats_netCDF_IO.o initialize.o parameters.o forward_model.o spectral_coefficients.o radiance.o 


# -------------------------------
# Create tarball for distribution
# -------------------------------

TAR_FILE = $(EXE_FILE)_software.tar

tar:
	$(TARBALL_CREATE) $(TAR_FILE) ${OBJ_FILES:.o=.f90}
	$(TARBALL_APPEND) $(TAR_FILE) makefile
	$(TARBALL_APPEND) $(TAR_FILE) make.macros make.rules
	compress $(TAR_FILE)



#-----------------------------------------------------------------------------
#                          -- Define default rules --
#-----------------------------------------------------------------------------

include make.rules

