DEVICE, TRUE_COLOR=24
DEVICE, RETAIN=2, DECOMP=0 
WINDOW, /FREE, /PIXMAP, COLORS = -5
PLOT, [ 0 ]
WDELETE, !D.WINDOW
DEVICE, SET_CHARACTER_SIZE = [ 6, 9 ]
PRINT, 'Number of colors is ', !D.N_COLORS
PRINT, 'Color table size is ', !D.TABLE_SIZE
COLORS
COMPILE_OPT DEFINT32, STRICTARR
