#==============================================================================
#
# Makefile for pCRTM K-Matrix Model Example
#
#==============================================================================

#-----------------------------------------------------------------------------
#                          -- Define macros --
#-----------------------------------------------------------------------------

include make.macros


# -------------
# This makefile
# -------------

MAKE_FILE = makefile


# ---------------
# Executable file
# ---------------

EXE_FILE = K_Matrix_Model_Example


# ------------
# Object files
# ------------

UTILITY_OBJ_FILES = Type_Kinds.o \
                    File_Utility.o \
                    Message_Handler.o \
                    Compare_Float_Numbers.o \
                    Endian_Utility.o \
                    Binary_File_Utility.o
SPCCOEFF_OBJ_FILES = SpcCoeff_Define.o \
                     SpcCoeff_Binary_IO.o
TAUCOEFF_OBJ_FILES = TauCoeff_Define.o \
                     TauCoeff_Binary_IO.o
pCRTM_OBJ_FILES = parameters.o \
                  sensor_planck_routines.o \
                  spectral_coefficients.o \
                  transmittance_coefficients.o \
                  initialize.o \
                  absorber_profile.o \
                  predictors.o \
                  transmittance.o \
                  radiance.o \
                  forward_model.o \
                  k_matrix_model.o

OBJ_FILES = $(UTILITY_OBJ_FILES) \
            $(SPCCOEFF_OBJ_FILES) \
            $(TAUCOEFF_OBJ_FILES) \
            $(pCRTM_OBJ_FILES) \
            $(EXE_FILE).o


# -----------------------------
# The profile data include file
# -----------------------------

INCLUDE_FILE = Profile.inc

INCLUDES = -I.



#-----------------------------------------------------------------------------
#                          -- Define dependecies --
#-----------------------------------------------------------------------------

# ---------------------
# Make based on OS type
# ---------------------

all:
	@echo "OS type detected: "`uname -s`
	@case `uname -s` in \
	  "SunOS")   make -f $(MAKE_FILE) test_program $(SUNOS_FLAGS) ;; \
	  "AIX")     make -f $(MAKE_FILE) test_program $(AIX_FLAGS) ;; \
	  "IRIX64" ) make -f $(MAKE_FILE) test_program $(IRIX64_FLAGS) ;; \
	  "Linux" )  make -f $(MAKE_FILE) test_program $(Linux_FLAGS) ;; \
	  *) echo "This system is not supported" ;; \
	esac



# ----------------
# Make the program
# ----------------

test_program: $(OBJ_FILES)
	$(FL) $(OBJ_FILES) $(EXTRA_FL_FLAGS) $(FL_FLAGS) $(EXE_FILE)



# --------
# Clean up
# --------

clean:
	$(REMOVE) $(OBJ_FILES) $(EXE_FILE) *.mod *.MOD *.stb


# ---------------
# Dependency list
# ---------------

Type_Kinds.o : Type_Kinds.f90
File_Utility.o : File_Utility.f90
Message_Handler.o : Message_Handler.f90 File_Utility.o
Compare_Float_Numbers.o : Compare_Float_Numbers.f90 Type_Kinds.o
Endian_Utility.o : Endian_Utility.f90 Type_Kinds.o
Binary_File_Utility.o : Binary_File_Utility.f90 Type_Kinds.o File_Utility.o Message_Handler.o Endian_Utility.o

parameters.o : parameters.f90 Type_Kinds.o
spectral_coefficients.o : spectral_coefficients.f90 Type_Kinds.o Message_Handler.o parameters.o SpcCoeff_Define.o SpcCoeff_Binary_IO.o
transmittance_coefficients.o : transmittance_coefficients.f90 Type_Kinds.o Message_Handler.o parameters.o TauCoeff_Define.o TauCoeff_Binary_IO.o
initialize.o : initialize.f90 Message_Handler.o transmittance_coefficients.o spectral_coefficients.o
absorber_profile.o : absorber_profile.f90 Type_Kinds.o parameters.o
predictors.o : predictors.f90 Type_Kinds.o Message_Handler.o parameters.o
transmittance.o : transmittance.f90 Type_Kinds.o parameters.o transmittance_coefficients.o
sensor_planck_routines.o : sensor_planck_routines.f90 Type_Kinds.o parameters.o spectral_coefficients.o
radiance.o : radiance.f90 Type_Kinds.o parameters.o spectral_coefficients.o sensor_planck_routines.o
forward_model.o : forward_model.f90 Type_Kinds.o Message_Handler.o parameters.o spectral_coefficients.o absorber_profile.o predictors.o transmittance.o radiance.o
k_matrix_model.o : k_matrix_model.f90 Type_Kinds.o Message_Handler.o parameters.o spectral_coefficients.o absorber_profile.o predictors.o transmittance.o radiance.o forward_model.o

SpcCoeff_Define.o : SpcCoeff_Define.f90 Type_Kinds.o Message_Handler.o Compare_Float_Numbers.o
SpcCoeff_Binary_IO.o : SpcCoeff_Binary_IO.f90 Type_Kinds.o File_Utility.o Message_Handler.o SpcCoeff_Define.o Binary_File_Utility.o
TauCoeff_Define.o : TauCoeff_Define.f90 Type_Kinds.o Message_Handler.o Compare_Float_Numbers.o
TauCoeff_Binary_IO.o : TauCoeff_Binary_IO.f90 Type_Kinds.o File_Utility.o Message_Handler.o TauCoeff_Define.o Binary_File_Utility.o

$(EXE_FILE).o : $(EXE_FILE).f90 Type_Kinds.o Message_Handler.o initialize.o parameters.o k_matrix_model.o

$(EXE_FILE) : $(INCLUDE_FILE)


# -------------------------------
# Create tarball for distribution
# -------------------------------

TAR_FILE = pCRTM_$(EXE_FILE)_software.tar

DATA_FILE_TAGS = amsua_n17 \
                 hirs3_n17 \
                 ssmis_f16

tar:
	$(TARBALL_CREATE) $(TAR_FILE) ${OBJ_FILES:.o=.f90}
	$(TARBALL_APPEND) $(TAR_FILE) makefile
	$(TARBALL_APPEND) $(TAR_FILE) make.macros make.rules
	$(TARBALL_APPEND) $(TAR_FILE) $(INCLUDE_FILE)
	@for file_tag in ${DATA_FILE_TAGS}; do \
	  $(TARBALL_APPEND) $(TAR_FILE) $$file_tag.results ; \
	  $(TARBALL_APPEND) $(TAR_FILE) $$file_tag.*.bin.*Endian ; \
	done
	compress $(TAR_FILE)



#-----------------------------------------------------------------------------
#                          -- Define default rules --
#-----------------------------------------------------------------------------

include make.rules

