#!/bin/sh

TYPE="create"
if [ $# -gt 0 ]; then
  if [ "$1" = "remove" ]; then
    TYPE="remove"
  fi
fi

INCLUDE_FILES="make.macros make.rules"
SRC_FILES="Timing_Utility.f90 CRTM_Test_Utility.f90"
USER_DATA_FILES="ECMWF-Atmosphere.Cloud.Aerosol.bin ECMWF-Surface.bin"
COEFF_DATA_FILES="EmisCoeff.bin AerosolCoeff.bin CloudCoeff.bin"
COEFF_DATA_TAG="amsua_n17 hirs3_n17 ssmis_f16 imgr_g11"
DATA_ENDIAN_TAG="Big_Endian"
TEST_DIRS="Forward Tangent_Linear Adjoint K_Matrix"

if [ "${TYPE}" = "create" ]; then
  linkfiles ${CRTM_SOURCE_ROOT} ${INCLUDE_FILES}
  for DIR in ${TEST_DIRS}; do
    cd ${DIR}
    linkfiles ${CRTM_SOURCE_ROOT} ${SRC_FILES}
    linkfiles -d ${DATA_ENDIAN_TAG} ${CRTM_SOURCE_ROOT} ${USER_DATA_FILES}
    linkfiles -d ${DATA_ENDIAN_TAG} ${CRTM_FIXFILE_ROOT} ${COEFF_DATA_FILES}
    for TAG in ${COEFF_DATA_TAG}; do \
      linkfiles -d ${DATA_ENDIAN_TAG} ${CRTM_FIXFILE_ROOT} ${TAG}.SpcCoeff.bin
      linkfiles -d ${DATA_ENDIAN_TAG} ${CRTM_FIXFILE_ROOT} ${TAG}.TauCoeff.bin
    done
    cd ..
  done
else
  unlinkfiles ${INCLUDE_FILES}
  for DIR in ${TEST_DIRS}; do
    cd ${DIR}
    unlinkfiles ${SRC_FILES}
    unlinkfiles ${USER_DATA_FILES}
    unlinkfiles ${COEFF_DATA_FILES}
    for TAG in ${COEFF_DATA_TAG}; do \
      unlinkfiles ${TAG}.SpcCoeff.bin
      unlinkfiles ${TAG}.TauCoeff.bin
    done
    cd ..
  done
fi



