#!/bin/sh

#
# run_baseline
#
# Shell script to run the CRTM baseline tests/verification. The makefiles
# do most of the work... this script just glues things together.
#
#
# CREATION HISTORY:
#       Written by:     Paul van Delst, CIMSS/SSEC 15-May-2007
#                       paul.vandelst@ssec.wisc.edu
#

SCRIPT_NAME=$(basename $0)
SUCCESS=0
FAILURE=1


# Remove the test report file
# ---------------------------
rm -f Test.report
if [ $? -ne 0 ]; then
  echo "${SCRIPT_NAME}: Error removing old test report log file!"
  exit ${FAILURE}
fi


# Invoke the master Makefile step by step
# ---------------------------------------
MAKE_STAGES="realclean link build run"
for STAGE in ${MAKE_STAGES}; do
  make ${STAGE}
  if [ $? -ne 0 ]; then
    echo "${SCRIPT_NAME}: Error in make ${STAGE} stage!"
    exit ${FAILURE}
  fi
done


# Check for model signal files
# ----------------------------
MODELS="Forward Tangent_Linear Adjoint K_Matrix"
i=0; n=0
for MODEL in ${MODELS}; do
  ((n++))
  if [ -f "${MODEL}/Test_${MODEL}.signal" ]; then
    ((i++))
  fi
done

echo; echo
if [ $i -eq $n ]; then
  echo "================================================================="
  echo "${SCRIPT_NAME}: SUCCESS! All tests passed!"
  echo "================================================================="
else
  echo "#################################################################"
  echo "${SCRIPT_NAME}: Failed test detected!"
  echo "#################################################################"
  exit ${FAILURE}
fi
echo; echo


# Clean up
# --------
# Run the realclean target
make realclean > /dev/null 2>&1

# Remove the main make include files
for FILE in ${MAKE_INCLUDES}; do
  if [ -h "${FILE}" ]; then
    rm ${FILE} > /dev/null 2>&1
  fi
done

exit ${SUCCESS}
