#!/bin/sh

PREP=pp
PREFIXES="get put"

for PREFIX in ${PREFIXES}; do

  ${PREP} ${PREFIX}_netCDF_Variable.rank.ppinput        ${PREFIX}_netCDF_Variable.rank.ppoutput
  ${PREP} ${PREFIX}_netCDF_Variable.rank_char.ppinput   ${PREFIX}_netCDF_Variable.rank_char.ppoutput char
  ${PREP} ${PREFIX}_netCDF_Variable.scalar.ppinput      ${PREFIX}_netCDF_Variable.scalar.ppoutput
  ${PREP} ${PREFIX}_netCDF_Variable.scalar_char.ppinput ${PREFIX}_netCDF_Variable.scalar_char.ppoutput char

  cat ${PREFIX}_netCDF_Variable.scalar.ppoutput \
      ${PREFIX}_netCDF_Variable.scalar_char.ppoutput \
      ${PREFIX}_netCDF_Variable.rank.ppoutput \
      ${PREFIX}_netCDF_Variable.rank_char.ppoutput > ${PREFIX}_netCDF_Variable
  rm ${PREFIX}_netCDF_Variable.scalar.ppoutput \
     ${PREFIX}_netCDF_Variable.scalar_char.ppoutput \
     ${PREFIX}_netCDF_Variable.rank.ppoutput \
     ${PREFIX}_netCDF_Variable.rank_char.ppoutput

done

sed '/Insert_Get_netCDF_Variable/r get_netCDF_Variable' netCDF_Variable_Utility.Header_and_Documentation > tmp_file1
sed '/Insert_Get_netCDF_Variable/d ' tmp_file1 > tmp_file2
rm -f tmp_file1
sed '/Insert_Put_netCDF_Variable/r put_netCDF_Variable' tmp_file2 > tmp_file3
rm -f tmp_file2
sed '/Insert_Put_netCDF_Variable/d ' tmp_file3 > netCDF_Variable_Utility.f90
rm -f tmp_file3

rm -f get_netCDF_Variable put_netCDF_Variable


