.compile assert      
.compile mgutclirunner__define
.compile mguttestsuite__define
.compile mguthtmlrunner__define     
.compile mguttestcase__define
.compile mgunit
.compile mguttestrunner__define
.compile mgutcompoundrunner__define.pro
.compile mg_ansicode
.compile mg_src_root
.compile mg_options__define
