#!/bin/sh

# Unlink the non-sensor specific data files
COEFFDATA_LIST="EmisCoeff.bin AerosolCoeff.bin CloudCoeff.bin"
unlinkfiles ${COEFFDATA_LIST}

# Unlink in the sensor specific data files
COEFFTYPE_LIST="SpcCoeff TauCoeff"
for COEFFTYPE in ${COEFFTYPE_LIST}; do
  COEFFDATA_LIST=$(ls *.${COEFFTYPE}.bin)
  unlinkfiles ${COEFFDATA_LIST}
done


