#!/bin/sh


#-------------------------------------------------------------------------------
#                        -- USAGE DESCRIPTION FUNCTION --
#-------------------------------------------------------------------------------

usage()
{
  echo " Usage: run_AtmProfile_NC2BIN -l|b[fh]"
  echo
  echo "   Convert any netCDF format AtmProfile files in the current"
  echo "   directory to Binary format. File with the suffix *.AtmProfile.nc"
  echo "   are converted into *.AtmProfile.bin files."
  echo
  echo "    l       Produce little-endian binary output files"
  echo
  echo "    b       Produce big-endian binary output files"
  echo
  echo "    f       Force overwrite of output file if it already exists."
  echo "            Default behaviour is to skip conversion if the output"
  echo "            file is already present."
  echo
  echo "    h       Print this message and exit"
  echo
}


#-------------------------------------------------------------------------------
#                              -- DEFINE DEFAULTS --
#-------------------------------------------------------------------------------

  ENDIAN_TYPE="NONE"
  OVERWRITE="NO"



#-------------------------------------------------------------------------------
#                       -- PARSE THE COMMAND LINE OPTIONS --
#-------------------------------------------------------------------------------

  while getopts :hlbf OPTVAL; do


    # --------------------------------------------
    # If option argument looks like another option
    # exit the loop
    # --------------------------------------------

    case ${OPTARG} in
      -*) break;;
    esac


    # ----------------------------
    # Parse the valid options here
    # ----------------------------

    case ${OPTVAL} in
      l)  ENDIAN_TYPE="little";;
      b)  ENDIAN_TYPE="big";;
      f)  OVERWRITE="YES";;
      h)  usage
          exit 0;;
      :|\?) OPTVAL=${OPTARG}
            break;;
    esac

  done


  # ----------------------------
  # Remove the options processed
  # ----------------------------

  shift `expr ${OPTIND} - 1`


  # ------------------------------------------
  # Now output invalidities based on OPTVAL
  # Need to do this as getopts does not handle
  # the situations where an option is passed
  # as an argument to another option.
  # ------------------------------------------

  case ${OPTVAL} in


    # --------------------------------------------
    # If OPTVAL contains nothing, then all options
    # have been successfully parsed
    # --------------------------------------------

    \?) if [ $# -ne 0 ]; then
          ( echo " Invalid argument(s) $*" ; echo ; usage ) | more
          #usage | more
          exit 2
        fi;;


    # --------------
    # Invalid option
    # --------------

    ?) ( echo " Invalid option '-${OPTARG}'" ; usage ) | more
       exit 2;;

  esac


  # ---------------------------------------
  # Check that an endian type was specified
  # ---------------------------------------

  if [ ${ENDIAN_TYPE} = "NONE" ]; then
    ( echo " Must specify and endian type, -l or -b" ; echo ; usage ) | more
    exit 2
  fi


#------------------------------------------------------------------------------#
#                       -- ASSIGN PROCESSING PARAMETERS --                     #
#------------------------------------------------------------------------------#

  EXE_FILE="AtmProfile_NC2BIN.${ENDIAN_TYPE}_endian"
  LOG_FILE="${EXE_FILE}.log"



#------------------------------------------------------------------------------#
#                  -- BEGIN LOOP OVER netCDF AtmProfile FILES --               #
#------------------------------------------------------------------------------#

  for NC_FILE in `ls *.AtmProfile.nc`; do


    # ----------------------
    # Create binary filename
    # ----------------------

    BIN_FILE="`basename ${NC_FILE} .nc`.bin.${ENDIAN_TYPE}_endian"


    # --------------------------------------
    # Check to see if the output file exists
    # --------------------------------------

    if [ -f ${BIN_FILE} -a ${OVERWRITE} = "NO" ]; then
      echo " Output file ${BIN_FILE} already exists. Skipping to next file..."
      continue
    fi


    # ----------------
    # Convert the file
    # ----------------

    echo " Converting ${NC_FILE} to ${ENDIAN_TYPE} endian binary format file ${BIN_FILE}..."
    ${EXE_FILE} <<-NoMoreInput >> ${LOG_FILE}
	${NC_FILE}
	${BIN_FILE}
	NoMoreInput
  done

exit


#-------------------------------------------------------------------------------
#                          -- MODIFICATION HISTORY --
#-------------------------------------------------------------------------------
#
# $Id: run_AtmProfile_NC2BIN,v 1.1 2004/08/27 17:25:44 paulv Exp $
#
# $Date: 2004/08/27 17:25:44 $
#
# $Revision: 1.1 $
#
# $Name:  $
#
# $State: Exp $
#
# $Log: run_AtmProfile_NC2BIN,v $
# Revision 1.1  2004/08/27 17:25:44  paulv
# Initial checkin.
#
#
#
#

