#==============================================================================
#
# Makefile for CRTM K-matrix model test program
#
# $Id$
#
#==============================================================================

# Define the executable file
EXE_FILE = Test_K_Matrix

# include the common make components
include ../make.common

# include the dependency list
include make.dependencies
