#!/bin/sh

#
# The following directory structure is created:
#
#  Transmittance_Production
#    |
#    |-- SRF_Data (*1)
#    |
#    `-- Data_Runs
#          |
#          |-- UMBC
#          |     |
#          |     |-- SRF_Data (link to *1)
#          |     `-- TAPE5_files
#          |
#          |-- CIMSS
#          |     |
#          |     |-- SRF_Data (link to *1)
#          |     `-- TAPE5_files
#          |
#          `-- ECMWF
#                |
#                |-- SRF_Data (link to *1)
#                `-- TAPE5_files
#



SCRIPT_NAME="`basename $0`"


# ABSOLUTE directory definitions
# ------------------------------
# The root directory/filesystem where all
# the software and fixed data is kept
if [ -z "${ARCHIVE_ROOT_DIR}" ]; then
  ARCHIVE_ROOT_DIR="/global/save/${USER}"
fi

# The root directory/filesystem where the
# TauProd datafiles will be stored
if [ -z "${HOME_ROOT_DIR}" ]; then
  HOME_ROOT_DIR="/global/noscrub/${USER}"
fi


# RELATIVE subdirectory names
# ---------------------------
# The transmittance production directory
TAUPROD_ROOT_DIR="TauProd"

# Other directory names
SRF_DATA_DIR="SRF_Data"
DATA_RUNS_DIR="Data_Runs"
TAPE5_DIR="TAPE5_files"
TAUPROFILE_DATA_DIR="TauProfile_data"
SRC_DIR="src/CRTM/trunk"
IR_TAUPROD_SRC_DIR="${SRC_DIR}/${TAUPROD_ROOT_DIR}/Infrared"

# The SensorInfo filename and directory
SENSORINFO_DIR="${SRC_DIR}/Utility/InstrumentInfo/SensorInfo"
SENSORINFO_FILE="SensorInfo"


# Define the profile set tag names
# --------------------------------
PROFILE_SET_TAGS="UMBC CIMSS ECMWF"


# Save the current directory location
# -----------------------------------
CURRENT_DIR=${PWD}


# Make and install all the Fortran95 software
# -------------------------------------------
cd ${HOME}/${IR_TAUPROD_SRC_DIR}
make
cd ${CURRENT_DIR}


# Install LBLRTM
# --------------
Install_LBLRTM
if [ $? -ne 0 ]; then
  echo "${SCRIPT_NAME}: Error installing LBLRTM"
  exit 2
fi


# -----------------------------------
# Install TauProd on ${HOME_ROOT_DIR}
# -----------------------------------

# Change to the root directory/filesystem on
# which the TauProd data will be STORED
# ------------------------------------------
cd ${HOME_ROOT_DIR}
if [ $? -ne 0 ]; then
  echo "${SCRIPT_NAME}: Error changing to ${HOME_ROOT_DIR} directory from ${PWD}"
  exit 2
fi


# Create TauProd directory if it doesn't already exist
# ----------------------------------------------------
if [ ! -d ${TAUPROD_ROOT_DIR} ]; then
  mkdir ${TAUPROD_ROOT_DIR}
  if [ $? -ne 0 ]; then
    echo "${SCRIPT_NAME}: Error creating ${TAUPROD_ROOT_DIR} directory in ${PWD}"
    exit 2
  fi
fi

# Enter TauProd directory for file copying
cd ${TAUPROD_ROOT_DIR}
if [ $? -ne 0 ]; then
  echo "${SCRIPT_NAME}: Error changing to ${TAUPROD_ROOT_DIR} directory from ${PWD}"
  exit 2
fi


# Copy over SRF data files
# ------------------------
echo
echo " Copying SRF data to ${PWD}/${SRF_DATA_DIR}..."
cp -r ${ARCHIVE_ROOT_DIR}/${SRF_DATA_DIR} .
if [ $? -ne 0 ]; then
  echo "${SCRIPT_NAME}: Error copying SRF data directory"
  exit 2
fi


# Copy over Master SensorInfo data file
# -------------------------------------
echo
echo " Copying SensorInfo datafile to ${PWD}..."
if [ ! -f ${SENSORINFO_FILE} ]; then
  cp ${ARCHIVE_ROOT_DIR}/${SENSORINFO_DIR}/${SENSORINFO_FILE} .
  if [ $? -ne 0 ]; then
    echo "${SCRIPT_NAME}: Error copying ${SENSORINFO_FILE}"
    exit 2
  fi
fi


# ----------------------------------
# Set up the profile set directories
# ----------------------------------
echo
echo " Setting up the profile set subdirectories..."

# Create the Data_Runs directory if it doesn't exist
# --------------------------------------------------
if [ ! -d ${DATA_RUNS_DIR} ]; then
  mkdir ${DATA_RUNS_DIR}
  if [ $? -ne 0 ]; then
    echo "${SCRIPT_NAME}: Error creating ${DATA_RUNS_DIR} directory in ${PWD}"
    exit 2
  fi

fi

# Enter Data_Runs directory
cd ${DATA_RUNS_DIR}
if [ $? -ne 0 ]; then
  echo "${SCRIPT_NAME}: Error changing to ${DATA_RUNS_DIR} root directory from ${PWD}"
  exit 2
fi


# Loop over the different profile sets
# ------------------------------------
for PROFILE_SET in ${PROFILE_SET_TAGS}; do


  # Create the profile set directory if it doesn't exist
  # ----------------------------------------------------
  if [ ! -d ${PROFILE_SET} ]; then
    mkdir ${PROFILE_SET}
    if [ $? -ne 0 ]; then
      echo "${SCRIPT_NAME}: Error creating ${PROFILE_SET} directory in ${PWD}"
      exit 2
    fi
  fi

  # Enter the profile set directory
  cd ${PROFILE_SET}
  if [ $? -ne 0 ]; then
    echo "${SCRIPT_NAME}: Error changing to ${PROFILE_SET} directory from ${PWD}"
    exit 2
  fi


  # Copy TAPE5 files for this profile set
  # -------------------------------------
  # Create the TAPE5 files directory if it doesn't exist
  if [ ! -d ${TAPE5_DIR} ]; then
    mkdir ${TAPE5_DIR}
    if [ $? -ne 0 ]; then
      echo "${SCRIPT_NAME}: Error creating ${TAPE5_DIR} directory in ${PWD}"
      exit 2
    fi
  fi

  # Enter the TAPE5 directory
  cd ${TAPE5_DIR}
  if [ $? -ne 0 ]; then
    echo "${SCRIPT_NAME}: Error changing to ${TAPE5_DIR} directory from ${PWD}"
    exit 2
  fi

  # Copy over TAPE5 data files
  cp ${ARCHIVE_ROOT_DIR}/${IR_TAUPROD_SRC_DIR}/Create_LBLRTM_Input_Files/${TAPE5_DIR}/${PROFILE_SET}_fixed/TAPE5.* .
  if [ $? -ne 0 ]; then
    echo "${SCRIPT_NAME}: Error copying ${PROFILE_SET} TAPE5 files to ${PWD}"
    exit 2
  fi
  
  # Return to current profile set directory
  cd ..

  
  # Link in SensorInfo for this profile set
  # ---------------------------------------
  ln -sf ${HOME_ROOT_DIR}/${TAUPROD_ROOT_DIR}/SensorInfo .
  if [ $? -ne 0 ]; then
    echo "${SCRIPT_NAME}: Error linking SensorInfo into ${PROFILE_SET} directory. Continuing..."
  fi


  # Create SRF directory for this profile set
  # -----------------------------------------
  if [ ! -d ${SRF_DATA_DIR} ]; then
    mkdir ${SRF_DATA_DIR}
    if [ $? -ne 0 ]; then
      echo "${SCRIPT_NAME}: Error creating ${SRF_DATA_DIR} in ${PROFILE_SET} directory. Continuing..."
    fi
  fi

  
  # Create final TauProfile directory for this profile set
  # (This is where the output from the process_TauProfile_files
  # script goes)
  # -----------------------------------------------------------
  if [ ! -d ${TAUPROFILE_DATA_DIR} ]; then
    mkdir ${TAUPROFILE_DATA_DIR}
    if [ $? -ne 0 ]; then
      echo "${SCRIPT_NAME}: Error creating ${TAUPROFILE_DATA_DIR} in ${PROFILE_SET} directory. Continuing..."
    fi
  fi
  
  # Return to Data_Runs directory
  cd ..

done


# Return to the start directory
# -----------------------------
cd ${CURRENT_DIR}

