#!/bin/sh

#-------------------------------------------------------------------------------
#                        -- USAGE DESCRIPTION FUNCTION --
#-------------------------------------------------------------------------------

usage()
{
  echo
  echo " Usage: Start_Processing [-h] [-p profile_begin[:profile_end]]"
  echo "                         [-t TAPE3_index_list] [-r Descriptor]"
  echo
  echo "   -h           Print this message and exit"
  echo
  echo "   -p           Use this option to specify the begin and end profile limits"
  echo "                for the calculation."
  echo "                Default action is determined by defaults file."
  echo
  echo "   -t           Use this option to specify the LBLRTM TAPE3 index list"
  echo "                to process."
  echo "                Valid TAPE3 indices are:"
  echo "                   1-7 == individual molecule numbers (no continua)"
  echo "                   8   == all first seven molecules (no continua)"
  echo "                   9   == continua only"
  echo "                  10   == all first seven molecules (and their continua)"
  echo "                  11   == water vapor + ozone only (and their continua)"
  echo "                  12   == water vapor only (and it's continua)"
  echo "                  13   == dry gases. Everything but h2o and o3 (and their continua)"
  echo "                  14   == ozone only (and it's continua)"
  echo "                  15   == water vapor continua only"
  echo "                If specifying more than one index, the list *must* be enclosed"
  echo "                in quotes."
  echo "                Default action is determined by defaults file."
  echo
  echo "   -r           Use this option to specify the predefined band limits for"
  echo "                certain instruments"
  echo "                Valid (case sensitive) descriptors are:"
  echo "                  BROADBAND == Broadband instrument LBL calcs are done"
  echo "                  AIRS      == High resolution LBL calcs for AIRS"
  echo "                  SSU       == High resolution LBL calcs over a very narrow"
  echo "                               spectral region for SSU"
  echo "                The default selection is BROADBAND"
  echo
}

#-------------------------------------------------------------------------------
#                              -- DEFINE DEFAULTS --
#-------------------------------------------------------------------------------

  # --------------------------
  # The default run descriptor
  # --------------------------

  RUN_DESCRIPTOR="BROADBAND"


  # ------------------------------------------------
  # Default processing values from the defaults file
  # ------------------------------------------------

  # -- Defaults file and required quantities
  DEFAULTS_FILE="Transmittance_Production.processing_defaults"
  DEFAULTS_LIST="TAPE3_LIST PROFILE1 PROFILE2"

  # -- Check existence of defaults file
  if [ ! -f ${DEFAULTS_FILE} ]; then
    echo "${DEFAULTS_FILE} file not found."
    exit 1
  fi

  # -- Get defaults from file
  for ITEM_NAME in ${DEFAULTS_LIST}; do

    ITEM_VALUE=`grep ":${ITEM_NAME}:" ${DEFAULTS_FILE} | cut -d":" -f3`

    case "${ITEM_NAME}" in

      # -- The TAPE3 list
      TAPE3_LIST) TAPE3_LIST=${ITEM_VALUE};;

      # -- Default PROFILE limits
      PROFILE1) PROFILE1=${ITEM_VALUE};;
      PROFILE2) PROFILE2=${ITEM_VALUE};;

      *) ;; # Ignore invalid default
    esac

  done


#-------------------------------------------------------------------------------
#                       -- PARSE THE COMMAND LINE OPTIONS --
#-------------------------------------------------------------------------------

  while getopts :hp:t:r: OPTVAL; do


    # --------------------------------------------
    # If option argument looks like another option
    # exit the loop
    # --------------------------------------------

    case ${OPTARG} in
      -*) break;;
    esac


    # ----------------------------
    # Parse the valid options here
    # ----------------------------

    case ${OPTVAL} in
      p)  PROFILE_LIMITS=${OPTARG}
          PROFILE1=`echo ${PROFILE_LIMITS} | cut -d: -f1`
          PROFILE2=`echo ${PROFILE_LIMITS} | cut -d: -f2`;;
      t)  TAPE3_LIST=${OPTARG};;
      r)  RUN_DESCRIPTOR=${OPTARG};;
      h)  usage
          exit 0;;
      :|\?) OPTVAL=${OPTARG}
            break;;
    esac

  done


  # ----------------------------
  # Remove the options processed
  # ----------------------------

  shift `expr ${OPTIND} - 1`


  # ------------------------------------------
  # Now output invalidities based on OPTVAL
  # Need to do this as getopts does not handle
  # the situations where an option is passed
  # as an argument to another option.
  # ------------------------------------------

  case ${OPTVAL} in


    # --------------------------------------------
    # If OPTVAL contains nothing, then all options
    # have been successfully parsed
    # --------------------------------------------

    \?) if [ $# -ne 0 ]; then
          ( echo " Invalid argument(s) $*" ; usage ) | more
          #usage | more
          exit 2
        fi;;


    # ------------------------------------
    # Valid options, but missing arguments
    # ------------------------------------

    p|t|r) ( echo " '-${OPTVAL}' option requires an argument" ; usage ) | more
                 exit 2;;


    # --------------
    # Invalid option
    # --------------

    ?) ( echo " Invalid option '-${OPTARG}'" ; usage ) | more
       exit 2;;

  esac


#------------------------------------------------------------------------------#
#                   -- SPECIFY TIME AND INCREMENTS IN MINUTES --               #
#------------------------------------------------------------------------------#

  # -- Initialise start time in minutes from now
  START_TIME=1


  # -- Specify processing increment times in minutes.
  # --
  # -- PROCESS_TAUSPC_INCREMENT: This is the increment of time between starting 
  # --                           the LBLRTM runs via the process_tape5_files script
  # --                           and starting the LBL data processing via the
  # --                           process_TauSpc_files script
  # --
  # -- PROCESS_PROFILE_INCREMENT: This is the increment of time between starting 
  # --                            profile runs via the process_tape5_files script.
  case "${RUN_DESCRIPTOR}" in
    AIRS) PROCESS_TAUSPC_INCREMENT=45
          PROCESS_PROFILE_INCREMENT=35;;
    SSU) PROCESS_TAUSPC_INCREMENT=15
         PROCESS_PROFILE_INCREMENT=2;;
    *) RUN_DESCRIPTOR="BROADBAND"
#       PROCESS_TAUSPC_INCREMENT=30
#       PROCESS_PROFILE_INCREMENT=20;;
       PROCESS_TAUSPC_INCREMENT=10
       PROCESS_PROFILE_INCREMENT=2;;
  esac



#------------------------------------------------------------------------------#
#                           -- LOOP OVER PROFILES --                           #
#------------------------------------------------------------------------------#

  PROFILE=${PROFILE1}
  while [ ${PROFILE} -le ${PROFILE2} ]; do


    # -----------------------
    # Loop over molecule sets
    # -----------------------

    for MOLECULE_SET in ${TAPE3_LIST}; do


      # ------------------------------------------------------
      # Start the processing based on the RUN_DESCRIPTOR value
      # ------------------------------------------------------

      case ${RUN_DESCRIPTOR} in

        # -- Start the profile LBL calculations for the broadband SRF (not SSU)
        "BROADBAND") at now + ${START_TIME} minutes <<-NoMoreInput
	process_tape5_files -p ${PROFILE} -b 1:12 -t ${MOLECULE_SET}
	NoMoreInput
        : ;;

        # -- Start the profile LBL calculations for the AIRS bands
        "AIRS") at now + ${START_TIME} minutes <<-NoMoreInput
	process_tape5_files -p ${PROFILE} -b 6:46 -t ${MOLECULE_SET}
	process_tape5_files -p ${PROFILE} -b 67:88 -t ${MOLECULE_SET}
	NoMoreInput
        : ;;

        # -- Start the profile LBL calculations for the SSU
        "SSU") at now + ${START_TIME} minutes <<-NoMoreInput
	process_tape5_files -p ${PROFILE} -b 7 -t ${MOLECULE_SET}
	NoMoreInput
        : ;;

      esac


      # ------------------------------------
      # Increment the start time for the
      # process_TauSpc_files script to allow
      # the LBLRTM runs to complete
      # ------------------------------------

      START_TAUSPC_TIME=`expr ${START_TIME} + ${PROCESS_TAUSPC_INCREMENT}`


      # -----------------------------
      # Start the profile convolution
      # -----------------------------

      at now + ${START_TAUSPC_TIME} minutes <<-NoMoreInput
	process_TauSpc_files -p ${PROFILE} -t ${MOLECULE_SET}
	NoMoreInput


      # ------------------------------------
      # Output a message with the start time
      # ------------------------------------

      echo " ${RUN_DESCRIPTOR} bands processing for profile ${PROFILE}, molecule set ${MOLECULE_SET} starts in ${START_TIME} minutes..."

 
      # --------------------------------
      # Increment the start time for the
      # next profile run
      # --------------------------------

      START_TIME=`expr ${START_TIME} + ${PROCESS_PROFILE_INCREMENT}`

    done   # MOLECULE


    # ----------------------------
    # Increment the profile number
    # ----------------------------

    PROFILE=`expr ${PROFILE} + 1`

  done   # PROFILE



#-------------------------------------------------------------------------------
#                          -- MODIFICATION HISTORY --
#-------------------------------------------------------------------------------
#
# $Id: Start_Processing,v 1.11 2006/01/26 18:30:00 paulv Exp $
#
# $Date: 2006/01/26 18:30:00 $
#
# $Revision: 1.11 $
#
# $Name:  $
#
# $State: Exp $
#
# $Log: Start_Processing,v $
# Revision 1.11  2006/01/26 18:30:00  paulv
# - Updated AIRS band delimiters to handle altered frequency intervals.
#
# Revision 1.10  2006/01/05 17:03:59  paulv
# - Added separate time values for the different run descriptors.
#
# Revision 1.9  2005/12/27 21:28:02  paulv
# - Changed the Broadband band processing limits from 1:13 back to 1:12. The
#   problem in processing SEVIRI was not the band limits, but the MAX_N_BANDS
#   set in Tau_Production_Parameters.f90.
#
# Revision 1.8  2005/12/27 18:24:41  paulv
# - Changed end band for broadband runs from 12 to 13. This will allow SEVIRI
#   transmittances to be computed.
#
# Revision 1.7  2005/12/19 21:58:38  paulv
# - Major changes.
#   o Defaults fil is now read in.
#   o Command line arguments are now available to allow targeted specification
#     of the processing jobs to run.
#   o Added an SSU run option. Very narrow band calcs, so long processing times
#     were not needed.
#
# Revision 1.6  2004/04/08 17:50:24  paulv
# - ALL option now encompasses SEVIRI bands.
#
# Revision 1.5  2004/01/23 17:31:02  paulv
# - Increased maximum band number for ALL processing from 94 to 96 due to
#   NOAA-18 AVHRR.
# - Added ALL_SEVIRI test run type to create LBL band data for the SEVIRI
#   channel 5 which spans bands 26-61. It's a lot of extra calculation for
#   just one channel on one instrument, so it gets it's own defn.
# - Added some more documentation and a modification history.
#
# Revision 1.4  2003/09/09 18:40:11  paulv
# - Updated submit time method used to account for the SP being sometimes
#   very slow to complete execution.
# 
# Revision 1.3  2003/07/23 17:08:30  paulv
# - Added a separate time increment for the TAPE5 and TauSpc processing runs.
#
# Revision 1.2  2003/07/22 17:39:23  paulv
# - Added an extra optional argument to allow the bands processed to be
#   selectable on the command line rather than having to edit the file.
#
# Revision 1.1  2003/07/22 15:56:21  paulv
# Initial checkin.
#
#
