#!/bin/sh

TYPE="create"
if [ $# -gt 0 ]; then
  if [ "$1" = "remove" ]; then
    TYPE="remove"
  fi
fi

USER_DATA_FILES="ECMWF-Atmosphere.Cloud.Aerosol.bin ECMWF-Surface.bin"
COEFF_DATA_FILES="EmisCoeff.bin AerosolCoeff.bin CloudCoeff.bin"
COEFF_DATA_TAG="amsua_n17 hirs3_n17 ssmis_f16 imgr_g11"
DATA_ENDIAN_TAG="Big_Endian"

if [ "${TYPE}" = "create" ]; then
  linkfiles -d ${DATA_ENDIAN_TAG} ${CRTM_SOURCE_ROOT} ${USER_DATA_FILES}
  linkfiles -d ${DATA_ENDIAN_TAG} ${CRTM_FIXFILE_ROOT} ${COEFF_DATA_FILES}
  for TAG in ${COEFF_DATA_TAG}; do \
    linkfiles -d ${DATA_ENDIAN_TAG} ${CRTM_FIXFILE_ROOT} ${TAG}.SpcCoeff.bin
    linkfiles -d ${DATA_ENDIAN_TAG} ${CRTM_FIXFILE_ROOT} ${TAG}.TauCoeff.bin
  done
else
  unlinkfiles ${INCLUDE_FILES}
  unlinkfiles ${USER_DATA_FILES}
  unlinkfiles ${COEFF_DATA_FILES}
  for TAG in ${COEFF_DATA_TAG}; do \
    unlinkfiles ${TAG}.SpcCoeff.bin
    unlinkfiles ${TAG}.TauCoeff.bin
  done
fi



