!
! LF_MWSSEMCoeff_Define
!
! Module defining the LF_MWSSEMCoeff data structure and containing routines to 
! manipulate it.
!
! CREATION HISTORY:
!       This file was automatically generated so edit at your own risk.
!       Generated by header.rb on 18-Mar-2007
!       Contact info:  Paul van Delst, CIMSS/SSEC
!                      paul.vandelst@ssec.wisc.edu
!

MODULE LF_MWSSEMCoeff_Define

  ! ------------------
  ! Environment set up
  ! ------------------
  ! Module use
  USE Type_Kinds           , ONLY: fp
  USE Message_Handler      , ONLY: SUCCESS, FAILURE, Display_Message
  USE Compare_Float_Numbers, ONLY: Compare_Float
  ! Disable implicit typing
  IMPLICIT NONE


  ! ------------
  ! Visibilities
  ! ------------
  ! Everything private by default
  PRIVATE
  ! Data structure definition
  PUBLIC :: LF_MWSSEMCoeff_type
  ! Structure procedures
  PUBLIC :: Associated_LF_MWSSEMCoeff
  PUBLIC :: Destroy_LF_MWSSEMCoeff
  PUBLIC :: Allocate_LF_MWSSEMCoeff
  PUBLIC :: Assign_LF_MWSSEMCoeff
  PUBLIC :: Equal_LF_MWSSEMCoeff
  PUBLIC :: Info_LF_MWSSEMCoeff
  PUBLIC :: CheckRelease_LF_MWSSEMCoeff
    

  ! -----------------
  ! Module parameters
  ! -----------------
  ! RCS Id for the module
  CHARACTER(*), PARAMETER :: MODULE_RCS_ID = &
  ! Literal constants
  REAL(fp), PARAMETER :: ZERO = 0.0_fp
  ! Current valid release and version numbers
  INTEGER, PARAMETER :: LF_MWSSEMCoeff_RELEASE = 1
  INTEGER, PARAMETER :: LF_MWSSEMCoeff_VERSION = 1

  ! -----------------------
  ! Derived type definition
  ! -----------------------
  TYPE :: LF_MWSSEMCoeff_type
    INTEGER :: n_Allocates=0
    ! Release and version information
    INTEGER :: Release = LF_MWSSEMCoeff_RELEASE
    INTEGER :: Version = LF_MWSSEMCoeff_VERSION
    ! Dimensions
    INTEGER :: n_Wind_Speeds = 0
    INTEGER :: n_Frequencies = 0
    ! Arrays
    REAL(fp), DIMENSION(:)  , POINTER :: Wind_Speed => NULL()
    REAL(fp), DIMENSION(:)  , POINTER :: Frequency  => NULL()
    REAL(fp), DIMENSION(:,:), POINTER :: sdd        => NULL()
  END TYPE LF_MWSSEMCoeff_type

CONTAINS
  SUBROUTINE Clear_LF_MWSSEMCoeff(LF_MWSSEMCoeff)
    TYPE(LF_MWSSEMCoeff_type), INTENT(IN OUT) :: LF_MWSSEMCoeff
  END SUBROUTINE Clear_LF_MWSSEMCoeff

  FUNCTION Associated_LF_MWSSEMCoeff( &
             LF_MWSSEMCoeff, &  ! Input
             ANY_Test      ) &  ! Optional input
           RESULT(Association_Status)
    ! Arguments
    TYPE(LF_MWSSEMCoeff_type), INTENT(IN) :: LF_MWSSEMCoeff
    INTEGER, OPTIONAL        , INTENT(IN) :: ANY_Test
    ! Function result
    LOGICAL :: Association_Status
    ! Local variables
    LOGICAL :: ALL_Test
    
    ! Defineault is to test ALL the pointer members
    ! for a true association status....
    ALL_Test = .TRUE.
    ! ...unless the ANY_Test argument is set.
    IF ( PRESENT( ANY_Test ) ) THEN
      IF ( ANY_Test == 1 ) ALL_Test = .FALSE.
    END IF
    
    ! Test the structure associations    
    Association_Status = .FALSE.
    IF (ALL_Test) THEN
      IF (ASSOCIATED(LF_MWSSEMCoeff%Wind_Speed) .AND. &
          ASSOCIATED(LF_MWSSEMCoeff%Frequency ) .AND. &
          ASSOCIATED(LF_MWSSEMCoeff%sdd       )) THEN
        Association_Status = .TRUE.
      END IF
    ELSE
      IF (ASSOCIATED(LF_MWSSEMCoeff%Wind_Speed) .OR. &
          ASSOCIATED(LF_MWSSEMCoeff%Frequency ) .OR. &
          ASSOCIATED(LF_MWSSEMCoeff%sdd       )) THEN
        Association_Status = .TRUE.
      END IF
    END IF
    
  END FUNCTION Associated_LF_MWSSEMCoeff
  
  FUNCTION Destroy_LF_MWSSEMCoeff( &
             LF_MWSSEMCoeff, &  ! Output
             No_Clear      , &  ! Optional input
             RCS_Id        , &  ! Revision control
             Message_Log   ) &  ! Error messaging
           RESULT(Error_Status)
    ! Arguments
    TYPE(LF_MWSSEMCoeff_type), INTENT(IN OUT) :: LF_MWSSEMCoeff
    INTEGER,      OPTIONAL   , INTENT(IN)     :: No_Clear
    CHARACTER(*), OPTIONAL   , INTENT(OUT)    :: RCS_Id
    CHARACTER(*), OPTIONAL   , INTENT(IN)     :: Message_Log
    ! Function result
    INTEGER :: Error_Status
    ! Local parameters
    CHARACTER(*), PARAMETER :: ROUTINE_NAME = 'Destroy_LF_MWSSEMCoeff'
    ! Local variables
    CHARACTER(256)  :: Message
    LOGICAL :: Clear
    INTEGER :: Allocate_Status
    
    ! Set up
    Error_Status = SUCCESS
    IF ( PRESENT( RCS_Id ) ) RCS_Id = MODULE_RCS_ID
    
    ! Default is to clear scalar members...
    Clear = .TRUE.
    ! ....unless the No_Clear argument is set
    IF ( PRESENT( No_Clear ) ) THEN
      IF ( No_Clear == 1 ) Clear = .FALSE.
    END IF
    
    ! Initialise the scalar members
    IF ( Clear ) CALL Clear_LF_MWSSEMCoeff(LF_MWSSEMCoeff)
    
    ! If ALL pointer members are NOT associated, do nothing
    IF ( .NOT. Associated_LF_MWSSEMCoeff(LF_MWSSEMCoeff) ) RETURN
    
    ! Deallocate the pointer members
    DEALLOCATE( LF_MWSSEMCoeff%Wind_Speed, &
                LF_MWSSEMCoeff%Frequency, &
                LF_MWSSEMCoeff%sdd, &
                STAT = Allocate_Status )
    IF ( Allocate_Status /= 0 ) THEN
      WRITE( Message, '("Error deallocating LF_MWSSEMCoeff. STAT = ",i0)') &
                      Allocate_Status
      Error_Status = FAILURE
      CALL Display_Message( &
             ROUTINE_NAME, &
             TRIM(Message), &
             Error_Status, &
             Message_Log=Message_Log )
      RETURN
    END IF

    ! Reset the dimension indicators
    LF_MWSSEMCoeff%n_Wind_Speeds = 0
    LF_MWSSEMCoeff%n_Frequencies = 0
    
    ! Decrement and test allocation counter
    LF_MWSSEMCoeff%n_Allocates = LF_MWSSEMCoeff%n_Allocates - 1
    IF ( LF_MWSSEMCoeff%n_Allocates /= 0 ) THEN
      WRITE( Message, '("Allocation counter /= 0, Value = ",i0)') &
                      LF_MWSSEMCoeff%n_Allocates
      Error_Status = FAILURE
      CALL Display_Message( &
             ROUTINE_NAME, &
             TRIM(Message), &
             Error_Status, &
             Message_Log=Message_Log )
      RETURN
    END IF
    
  END FUNCTION Destroy_LF_MWSSEMCoeff
  
  FUNCTION Allocate_LF_MWSSEMCoeff( &
             n_Wind_Speeds , &  ! Input
             n_Frequencies , &  ! Input
             LF_MWSSEMCoeff, &  ! Output
             RCS_Id        , &  ! Revision control
             Message_Log   ) &  ! Error messaging
           RESULT( Error_Status )
    ! Arguments
    INTEGER                  , INTENT(IN) :: n_Wind_Speeds
    INTEGER                  , INTENT(IN) :: n_Frequencies
    TYPE(LF_MWSSEMCoeff_type), INTENT(IN OUT) :: LF_MWSSEMCoeff
    CHARACTER(*), OPTIONAL   , INTENT(OUT)    :: RCS_Id
    CHARACTER(*), OPTIONAL   , INTENT(IN)     :: Message_Log
    ! Function result
    INTEGER :: Error_Status
    ! Local parameters
    CHARACTER(*), PARAMETER :: ROUTINE_NAME = 'Allocate_LF_MWSSEMCoeff'
    ! Local variables
    CHARACTER(256) :: Message
    INTEGER :: Allocate_Status
    
    ! Set up
    Error_Status = SUCCESS
    IF ( PRESENT( RCS_Id ) ) RCS_Id = MODULE_RCS_ID
    
    ! Check dimensions
    IF (n_Wind_Speeds < 1 .OR. &
        n_Frequencies < 1) THEN
      Error_Status = FAILURE
      CALL Display_Message( &
             ROUTINE_NAME, &
             'Input LF_MWSSEMCoeff dimensions must all be > 0.', &
             Error_Status, &
             Message_Log=Message_Log )
      RETURN
    END IF
    
    ! Check if ANY pointers are already associated.
    ! If they are, deallocate them but leave scalars.
    IF ( Associated_LF_MWSSEMCoeff( LF_MWSSEMCoeff, ANY_Test=1 ) ) THEN
      Error_Status = Destroy_LF_MWSSEMCoeff( &
                       LF_MWSSEMCoeff, &
                       No_Clear=1, &
                       Message_Log=Message_Log )
      IF ( Error_Status /= SUCCESS ) THEN
        Error_Status = FAILURE
        CALL Display_Message( &
               ROUTINE_NAME, &
               'Error deallocating LF_MWSSEMCoeff prior to allocation.', &
               Error_Status, &
               Message_Log=Message_Log )
        RETURN
      END IF
    END IF
    
    ! Perform the pointer allocation
    ALLOCATE( LF_MWSSEMCoeff%Wind_Speed(1:n_Wind_Speeds), &
              LF_MWSSEMCoeff%Frequency(1:n_Frequencies), &
              LF_MWSSEMCoeff%sdd(1:n_Wind_Speeds,1:n_Frequencies), &
              STAT = Allocate_Status )
    IF ( Allocate_Status /= 0 ) THEN
      WRITE(Message,'("Error allocating LF_MWSSEMCoeff data arrays. STAT = ",i0)') &
                    Allocate_Status
      Error_Status = FAILURE
      CALL Display_Message( &
             ROUTINE_NAME, &
             TRIM(Message), &
             Error_Status, &
             Message_Log=Message_Log )
      RETURN
    END IF
    
    ! Assign the dimensions
    LF_MWSSEMCoeff%n_Wind_Speeds = n_Wind_Speeds
    LF_MWSSEMCoeff%n_Frequencies = n_Frequencies
    
    ! Initialise the arrays
    LF_MWSSEMCoeff%Wind_Speed = ZERO
    LF_MWSSEMCoeff%Frequency  = ZERO
    LF_MWSSEMCoeff%sdd        = ZERO
    
    ! Increment and test the allocation counter
    LF_MWSSEMCoeff%n_Allocates = LF_MWSSEMCoeff%n_Allocates + 1
    IF ( LF_MWSSEMCoeff%n_Allocates /= 1 ) THEN
      WRITE( Message, '("Allocation counter /= 1, Value = ",i0)') &
                      LF_MWSSEMCoeff%n_Allocates
      Error_Status = FAILURE
      CALL Display_Message( &
             ROUTINE_NAME, &
             TRIM(Message), &
             Error_Status, &
             Message_Log=Message_Log )
      RETURN
    END IF
    
  END FUNCTION Allocate_LF_MWSSEMCoeff
  
  FUNCTION Assign_LF_MWSSEMCoeff( &
             LF_MWSSEMCoeff_in , &  ! Input
             LF_MWSSEMCoeff_out, &  ! Output
             RCS_Id            , &  ! Revision control
             Message_Log       ) &  ! Error messaging
           RESULT( Error_Status )
    ! Arguments
    TYPE(LF_MWSSEMCoeff_type), INTENT(IN)     :: LF_MWSSEMCoeff_in
    TYPE(LF_MWSSEMCoeff_type), INTENT(IN OUT) :: LF_MWSSEMCoeff_out
    CHARACTER(*), OPTIONAL   , INTENT(OUT)    :: RCS_Id
    CHARACTER(*), OPTIONAL   , INTENT(IN)     :: Message_Log
    ! Function result
    INTEGER :: Error_Status
    ! Local parameters
    CHARACTER(*), PARAMETER :: ROUTINE_NAME = 'Assign_LF_MWSSEMCoeff'
    ! Local variables
    INTEGER :: i1,i2

    ! Set up
    Error_Status = SUCCESS
    IF ( PRESENT( RCS_Id ) ) RCS_Id = MODULE_RCS_ID

    ! ALL *input* pointers must be associated
    IF ( .NOT. Associated_LF_MWSSEMCoeff( LF_MWSSEMCoeff_in ) ) THEN
      Error_Status = FAILURE
      CALL Display_Message( &
             ROUTINE_NAME, &
             'Some or all INPUT LF_MWSSEMCoeff_in pointer members are NOT associated.', &
             Error_Status, &
             Message_Log=Message_Log )
      RETURN
    END IF
    
    ! Allocate data arrays
    Error_Status = Allocate_LF_MWSSEMCoeff( LF_MWSSEMCoeff_in%n_Wind_Speeds, &
                                            LF_MWSSEMCoeff_in%n_Frequencies, &
                                            LF_MWSSEMCoeff_out, &
                                            Message_Log=Message_Log )
    IF ( Error_Status /= SUCCESS ) THEN
      Error_Status = FAILURE
      CALL Display_Message( &
             ROUTINE_NAME, &
             'Error allocating output structure', &
             Error_Status, &
             Message_Log=Message_Log )
      RETURN
    END IF
    
    ! Copy array data
    LF_MWSSEMCoeff_out%Wind_Speed = LF_MWSSEMCoeff_in%Wind_Speed
    LF_MWSSEMCoeff_out%Frequency  = LF_MWSSEMCoeff_in%Frequency
    LF_MWSSEMCoeff_out%sdd        = LF_MWSSEMCoeff_in%sdd
    
  END FUNCTION Assign_LF_MWSSEMCoeff
  
  FUNCTION Equal_LF_MWSSEMCoeff( &
             LF_MWSSEMCoeff_LHS, &  ! Input
             LF_MWSSEMCoeff_RHS, &  ! Input
             ULP_Scale         , &  ! Optional input
             RCS_Id            , &  ! Revision control
             Message_Log       ) &  ! Error messaging
           RESULT( Error_Status )
    ! Arguments
    TYPE(LF_MWSSEMCoeff_type), INTENT(IN)  :: LF_MWSSEMCoeff_LHS
    TYPE(LF_MWSSEMCoeff_type), INTENT(IN)  :: LF_MWSSEMCoeff_RHS
    INTEGER,      OPTIONAL   , INTENT(IN)  :: ULP_Scale
    CHARACTER(*), OPTIONAL   , INTENT(OUT) :: RCS_Id
    CHARACTER(*), OPTIONAL   , INTENT(IN)  :: Message_Log
    ! Function result
    INTEGER :: Error_Status
    ! Local parameters
    CHARACTER(*), PARAMETER :: ROUTINE_NAME = 'Equal_LF_MWSSEMCoeff'
    ! Local variables
    CHARACTER(256) :: Message
    INTEGER :: ULP
    INTEGER :: l, j
    INTEGER :: i1,i2

    ! Set up
    Error_Status = SUCCESS
    IF ( PRESENT( RCS_Id ) ) RCS_Id = MODULE_RCS_ID

    ! Default precision is a single unit in last place
    ULP = 1
    ! ... unless the ULP_Scale argument is set and positive
    IF ( PRESENT( ULP_Scale ) ) THEN
      IF ( ULP_Scale > 0 ) ULP = ULP_Scale
    END IF

    ! Check the structure association status
    IF ( .NOT. Associated_LF_MWSSEMCoeff( LF_MWSSEMCoeff_LHS ) ) THEN
      Error_Status = FAILURE
      CALL Display_Message( &
             ROUTINE_NAME, &
             'Some or all INPUT LF_MWSSEMCoeff_LHS pointer members are NOT associated.', &
             Error_Status, &
             Message_Log=Message_Log )
      RETURN
    END IF
    IF ( .NOT. Associated_LF_MWSSEMCoeff( LF_MWSSEMCoeff_RHS ) ) THEN
      Error_Status = FAILURE
      CALL Display_Message( &
             ROUTINE_NAME, &
             'Some or all INPUT LF_MWSSEMCoeff_RHS pointer members are NOT associated.', &
             Error_Status, &
             Message_Log=Message_Log )
      RETURN
    END IF
    
    ! Check dimensions
    IF (LF_MWSSEMCoeff_LHS%n_Wind_Speeds /= LF_MWSSEMCoeff_RHS%n_Wind_Speeds .OR. &
        LF_MWSSEMCoeff_LHS%n_Frequencies /= LF_MWSSEMCoeff_RHS%n_Frequencies) THEN
      Error_Status = FAILURE
      CALL Display_Message( &
             ROUTINE_NAME, &
             'Structure dimensions are different.', &
             Error_Status, &
             Message_Log=Message_Log )
      RETURN
    END IF

    ! Check the array components
    DO i1=1,LF_MWSSEMCoeff_LHS%n_Wind_Speeds
      IF ( .NOT. Compare_Float( LF_MWSSEMCoeff_LHS%Wind_Speed(i1), &
                                LF_MWSSEMCoeff_RHS%Wind_Speed(i1), &
                                ULP=ULP ) ) THEN
        WRITE(Message,'("LF_MWSSEMCoeff array component Wind_Speed values ",&
                        &"are different at index (",1(1x,i0),")")') &
                        i1
        Error_Status = FAILURE
        CALL Display_Message( &
               ROUTINE_NAME, &
               TRIM(Message), &
               Error_Status, &
               Message_Log=Message_Log )
        RETURN
      END IF
    END DO
    DO i1=1,LF_MWSSEMCoeff_LHS%n_Frequencies
      IF ( .NOT. Compare_Float( LF_MWSSEMCoeff_LHS%Frequency(i1), &
                                LF_MWSSEMCoeff_RHS%Frequency(i1), &
                                ULP=ULP ) ) THEN
        WRITE(Message,'("LF_MWSSEMCoeff array component Frequency values ",&
                        &"are different at index (",1(1x,i0),")")') &
                        i1
        Error_Status = FAILURE
        CALL Display_Message( &
               ROUTINE_NAME, &
               TRIM(Message), &
               Error_Status, &
               Message_Log=Message_Log )
        RETURN
      END IF
    END DO
    DO i2=1,LF_MWSSEMCoeff_LHS%n_Frequencies
      DO i1=1,LF_MWSSEMCoeff_LHS%n_Wind_Speeds
        IF ( .NOT. Compare_Float( LF_MWSSEMCoeff_LHS%sdd(i1,i2), &
                                  LF_MWSSEMCoeff_RHS%sdd(i1,i2), &
                                  ULP=ULP ) ) THEN
          WRITE(Message,'("LF_MWSSEMCoeff array component sdd values ",&
                          &"are different at index (",2(1x,i0),")")') &
                          i1,i2
          Error_Status = FAILURE
          CALL Display_Message( &
                 ROUTINE_NAME, &
                 TRIM(Message), &
                 Error_Status, &
                 Message_Log=Message_Log )
          RETURN
        END IF
      END DO
    END DO
    
  END FUNCTION Equal_LF_MWSSEMCoeff
  
  SUBROUTINE Info_LF_MWSSEMCoeff( &
               LF_MWSSEMCoeff, &  ! Input
               Info          , &  ! Output
               RCS_Id          )  ! Revision control
    ! Arguments
    TYPE(LF_MWSSEMCoeff_type), INTENT(IN)  :: LF_MWSSEMCoeff
    CHARACTER(*)             , INTENT(OUT) :: Info
    CHARACTER(*), OPTIONAL   , INTENT(OUT) :: RCS_Id
    ! Parameters
    INTEGER, PARAMETER :: CARRIAGE_RETURN = 13
    INTEGER, PARAMETER :: LINEFEED = 10
    ! Local variables
    CHARACTER(80)  :: FmtString
    CHARACTER(512) :: LongString

    ! Set up
    IF ( PRESENT( RCS_Id ) ) RCS_Id = MODULE_RCS_ID

    ! Write the required info to the local string
    FmtString='(a,1x,"LF_MWSSEMCoeff:",2x,&
               &"N_WIND_SPEEDS=",i0,2x,&
               &"N_FREQUENCIES=",i0,2x)'
    WRITE(LongString, FMT=FmtString) &
          ACHAR(CARRIAGE_RETURN)//ACHAR(LINEFEED), &
          LF_MWSSEMCoeff%n_Wind_Speeds, &
          LF_MWSSEMCoeff%n_Frequencies

    ! Trim the output based on the
    ! dummy argument string length
    Info = LongString(1:MIN( LEN(Info), LEN_TRIM(LongString) ))

  END SUBROUTINE Info_LF_MWSSEMCoeff
  
  FUNCTION CheckRelease_LF_MWSSEMCoeff( &
             LF_MWSSEMCoeff, &  ! Input
             RCS_Id        , &  ! Revision control
             Message_Log   ) &  ! Error messaging
           RESULT( Error_Status )
    ! Arguments
    TYPE(LF_MWSSEMCoeff_type), INTENT(IN)  :: LF_MWSSEMCoeff
    CHARACTER(*), OPTIONAL   , INTENT(OUT) :: RCS_Id
    CHARACTER(*), OPTIONAL   , INTENT(IN)  :: Message_Log
    ! Function result
    INTEGER :: Error_Status
    ! Local parameters
    CHARACTER(*), PARAMETER :: ROUTINE_NAME = 'CheckRelease_LF_MWSSEMCoeff'
    ! Local variables
    CHARACTER(256) :: Message

    ! Set up
    Error_Status = SUCCESS
    IF ( PRESENT( RCS_Id ) ) RCS_Id = MODULE_RCS_ID

    ! Check release is not too old
    IF ( LF_MWSSEMCoeff%Release < LF_MWSSEMCoeff_RELEASE ) THEN
      WRITE( Message, '( "A LF_MWSSEMCoeff data update is needed. ", &
                        &"LF_MWSSEMCoeff release is ", i0, &
                        &". Valid release is ",i0,"." )' ) &
                      LF_MWSSEMCoeff%Release, LF_MWSSEMCoeff_RELEASE
      Error_Status = FAILURE
      CALL Display_Message( &
             ROUTINE_NAME, &
             TRIM(Message), &
             Error_Status, &
             Message_Log=Message_Log )
      RETURN
    END IF

    ! Check release is not too new
    IF ( LF_MWSSEMCoeff%Release > LF_MWSSEMCoeff_RELEASE ) THEN
      WRITE( Message, '( "A LF_MWSSEMCoeff software update is needed. ", &
                        &"LF_MWSSEMCoeff release is ", i0, &
                        &". Valid release is ",i0,"." )' ) &
                      LF_MWSSEMCoeff%Release, LF_MWSSEMCoeff_RELEASE
      Error_Status = FAILURE
      CALL Display_Message( &
             ROUTINE_NAME, &
             TRIM(Message), &
             Error_Status, &
             Message_Log=Message_Log )
      RETURN
    END IF

  END FUNCTION CheckRelease_LF_MWSSEMCoeff

END MODULE LF_MWSSEMCoeff_Define
