#==============================================================================
#
# Makefile for CRTM Adjoint model test program
#
# $Id$
#
#==============================================================================

# Define the executable file
EXE_FILE = Test_Adjoint

# include the common make components
include ../make.common

# include the dependency list
include make.dependencies
