#!/bin/sh
#
#  NAME:
# 	Link_AtmProfile
#
#  PURPOSE:
#       Shell script file to link in the requested netCDF AtmProfile
#       datafile from the CRTM fixfile repository.
#
#  CALLING SEQUENCE:
#       Link_AtmProfile [-h] [-x] UMBC48 | ECMWF52 | ECMWF83 | CIMSS32 | Model6
#
#  ENVIRONMENT VARIABLES:
#       The following environment variables must be defined to use this script.
#
#       CRTM_FIXFILE_ROOT:  The directory location of a working copy of the
#                           CRTM fixfile repository.
#                           
#

# -----------------------------
# Error message output function
# -----------------------------
error_message()
{
  SCRIPT_NAME="`basename $0`"
  MESSAGE=$1
  echo; echo "${SCRIPT_NAME}(ERROR): ${MESSAGE}"
}

# --------------
# Usage function
# --------------
usage()
{
  echo
  echo "Usage: Link_AtmProfile [-h] [-x] AtmId [ AtmId_2 AtmId_3 ... AtmId_N ]"
  echo
  echo "  -h"
  echo "       Print this message."
  echo
  echo "  -x"
  echo "       Turn on execution tracing"
  echo
  echo "  AtmId [ AtmId_2 AtmId_3 ... AtmId_N ]"
  echo "       The identifier for the required AtmProfile data set to link."
  echo "       Valid identifiers are:"
  echo "         UMBC48 : The UMBC 48-profile data set."
  echo "         ECMWF52: The ECMWF 52-profile data set."
  echo "         ECMWF83: The ECMWF 83-profile data set."
  echo "         CIMSS32: The CIMSS 32-profile data set."
  echo "         Model6 : The Model 6-profile data set."
  echo
}


########################################################################
#                           MAIN SCRIPT BEGINS                         #
########################################################################

# Set up
# ------
SUCCESS=0
FAILURE=1


# Parse the command line options
# ------------------------------
while getopts :hx OPTVAL; do
  # Exit if option argument looks like another option
  case ${OPTARG} in
    -*) break;;
  esac
  # Parse the valid options
  case ${OPTVAL} in
    h) usage; exit ${SUCCESS};;
    x) set -x;;
    :|\?) OPTVAL=${OPTARG}; break;;
  esac
done
# Remove the options processed
shift $(expr ${OPTIND} - 1)
# Output invalidities based on OPTVAL
case ${OPTVAL} in
  # If OPTVAL contains nothing, then all options
  # have been successfully parsed and all that
  # remains are the arguments
  \?) if [ $# -lt 1 ]; then
        usage; error_message " Missing 'AtmId' argument(s)"
        exit ${FAILURE}
      fi;;
  # Invalid option
  ?) usage; error_message " Invalid option '-${OPTARG}'"; exit ${FAILURE};;
esac


# Assign command line arguments
# -----------------------------
ATMPROFILE_ID_LIST=$*


# Check that the mandatory envar is defined
# -----------------------------------------
if [ -z "${CRTM_FIXFILE_ROOT}" ]; then
  error_message "CRTM_FIXFILE_ROOT envar is not defined."
  exit ${FAILURE}
fi


# Set the AtmProfile directory name
# ---------------------------------
ATMPROFILE_DIR="${CRTM_FIXFILE_ROOT}/TauProd/AtmProfile"


# Loop over the AtmProfile ids to link
# ------------------------------------
RETURN_CODE=${SUCCESS}
for ATMPROFILE_ID in ${ATMPROFILE_ID_LIST}; do
  # Create the AtmProfile filename
  ATMPROFILE_FILE="${ATMPROFILE_ID}.AtmProfile.nc"
  # Check that the file exists, but keep going if it doesn't
  if [ ! -f ${ATMPROFILE_DIR}/${ATMPROFILE_FILE} ]; then
    error_message " AtmProfile datafile, ${ATMPROFILE_FILE}, not found in ${ATMPROFILE_DIR}. Skipping..."
    RETURN_CODE=${FAILURE}
    continue
  fi
  # Link it in
  if [ ! -f ${ATMPROFILE_FILE} ]; then
    ln -s ${ATMPROFILE_DIR}/${ATMPROFILE_FILE} .
    if [ $? -ne 0 ]; then
      error_message "Error occured linking ${ATMPROFILE_FILE} to ${PWD}"
      exit ${FAILURE}
    fi
  else
    error_message "${ATMPROFILE_FILE} file already exists in this directory. Skipping..."
    continue
  fi
done


# Done. Turn off execution tracing
# --------------------------------
set +x
exit ${RETURN_CODE}

