#==============================================================================
#
# Makefile for CRTM Test Initialization program
#
#==============================================================================

#-----------------------------------------------------------------------------
#                          -- Define macros --
#-----------------------------------------------------------------------------

include make.macros


# -------------
# This makefile
# -------------

MAKE_FILE = makefile


# ---------------
# Executable file
# ---------------

EXE_FILE = Test_Initialization


# ------------
# Object files
# ------------

UTILITY_OBJ_FILES = Type_Kinds.o \
                    File_Utility.o \
                    Message_Handler.o \
                    Compare_Float_Numbers.o \
                    Endian_Utility.o \
                    Binary_File_Utility.o

SPCCOEFF_OBJ_FILES = SpcCoeff_Define.o \
                     SpcCoeff_Binary_IO.o

TAUCOEFF_OBJ_FILES = TauCoeff_Define.o \
                     TauCoeff_Binary_IO.o

CLOUDCOEFF_OBJ_FILES = CloudCoeff_Define.o \
                       CloudCoeff_Binary_IO.o

AEROSOLCOEFF_OBJ_FILES = AerosolCoeff_Define.o \
                         AerosolCoeff_Binary_IO.o

EMISCOEFF_OBJ_FILES = EmisCoeff_Define.o \
                      EmisCoeff_Binary_IO.o

CRTM_COEFF_OBJ_FILES = CRTM_SpcCoeff.o \
                       CRTM_TauCoeff.o \
                       CRTM_CloudCoeff.o \
                       CRTM_AerosolCoeff.o \
                       CRTM_EmisCoeff.o

CRTM_CHANNELINFO_OBJ_FILES = CRTM_ChannelInfo_Define.o \
                             CRTM_ChannelInfo.o

CRTM_OBJ_FILES = CRTM_Parameters.o \
                 CRTM_LifeCycle.o

OBJ_FILES = $(UTILITY_OBJ_FILES) \
            $(SPCCOEFF_OBJ_FILES) \
            $(TAUCOEFF_OBJ_FILES) \
            $(CLOUDCOEFF_OBJ_FILES) \
            $(AEROSOLCOEFF_OBJ_FILES) \
            $(EMISCOEFF_OBJ_FILES) \
            $(CRTM_COEFF_OBJ_FILES) \
            $(CRTM_CHANNELINFO_OBJ_FILES) \
            $(CRTM_OBJ_FILES) \
            $(EXE_FILE).o



#-----------------------------------------------------------------------------
#                          -- Define dependecies --
#-----------------------------------------------------------------------------

# ---------------------
# Make based on OS type
# ---------------------

all:
	@echo "OS type detected: "`uname -s`
	@case `uname -s` in \
	  "SunOS")   make -f $(MAKE_FILE) test_program $(SUNOS_FLAGS) ;; \
	  "AIX")     make -f $(MAKE_FILE) test_program $(AIX_FLAGS) ;; \
	  "IRIX64" ) make -f $(MAKE_FILE) test_program $(IRIX64_FLAGS) ;; \
	  "Linux" )  make -f $(MAKE_FILE) test_program $(LINUX_FLAGS) ;; \
	  *) echo "This system is not supported" ;; \
       esac


# ----------------
# Make the program
# ----------------

test_program: $(OBJ_FILES)
	$(FL) $(OBJ_FILES) $(EXTRA_FL_FLAGS) $(FL_FLAGS) $(EXE_FILE)



# --------
# Clean up
# --------

clean:
	$(REMOVE) $(OBJ_FILES) *.mod *.MOD *.stb


# ---------------
# Dependency list
# ---------------

Type_Kinds.o : Type_Kinds.f90
File_Utility.o : File_Utility.f90
Message_Handler.o : Message_Handler.f90 File_Utility.o
Endian_Utility.o : Endian_Utility.f90 Type_Kinds.o
Compare_Float_Numbers.o : Compare_Float_Numbers.f90 Type_Kinds.o
Binary_File_Utility.o : Binary_File_Utility.f90 Type_Kinds.o File_Utility.o Message_Handler.o Endian_Utility.o

TauCoeff_Define.o : TauCoeff_Define.f90 Type_Kinds.o Message_Handler.o Compare_Float_Numbers.o
TauCoeff_Binary_IO.o : TauCoeff_Binary_IO.f90 Type_Kinds.o File_Utility.o Message_Handler.o Binary_File_Utility.o TauCoeff_Define.o
SpcCoeff_Define.o : SpcCoeff_Define.f90 Type_Kinds.o Message_Handler.o Compare_Float_Numbers.o
SpcCoeff_Binary_IO.o : SpcCoeff_Binary_IO.f90 Type_Kinds.o File_Utility.o Message_Handler.o Binary_File_Utility.o SpcCoeff_Define.o
CloudCoeff_Define.o : CloudCoeff_Define.f90 Type_Kinds.o Message_Handler.o Compare_Float_Numbers.o
CloudCoeff_Binary_IO.o : CloudCoeff_Binary_IO.f90 Type_Kinds.o File_Utility.o Message_Handler.o Binary_File_Utility.o CloudCoeff_Define.o
AerosolCoeff_Define.o : AerosolCoeff_Define.f90 Type_Kinds.o Message_Handler.o Compare_Float_Numbers.o
AerosolCoeff_Binary_IO.o : AerosolCoeff_Binary_IO.f90 Type_Kinds.o File_Utility.o Message_Handler.o Binary_File_Utility.o AerosolCoeff_Define.o
EmisCoeff_Define.o : EmisCoeff_Define.f90 Type_Kinds.o Message_Handler.o Compare_Float_Numbers.o
EmisCoeff_Binary_IO.o : EmisCoeff_Binary_IO.f90 Type_Kinds.o Message_Handler.o File_Utility.o Binary_File_Utility.o EmisCoeff_Define.o

CRTM_TauCoeff.o : CRTM_TauCoeff.f90 Type_Kinds.o Message_Handler.o TauCoeff_Define.o TauCoeff_Binary_IO.o CRTM_Parameters.o
CRTM_SpcCoeff.o : CRTM_SpcCoeff.f90 Type_Kinds.o Message_Handler.o SpcCoeff_Define.o SpcCoeff_Binary_IO.o CRTM_Parameters.o
CRTM_CloudCoeff.o : CRTM_CloudCoeff.f90 Type_Kinds.o Message_Handler.o CloudCoeff_Define.o CloudCoeff_Binary_IO.o CRTM_Parameters.o
CRTM_AerosolCoeff.o : CRTM_AerosolCoeff.f90 Type_Kinds.o Message_Handler.o AerosolCoeff_Define.o AerosolCoeff_Binary_IO.o CRTM_Parameters.o
CRTM_EmisCoeff.o : CRTM_EmisCoeff.f90 Type_Kinds.o Message_Handler.o EmisCoeff_Define.o EmisCoeff_Binary_IO.o

CRTM_ChannelInfo_Define.o : CRTM_ChannelInfo_Define.f90 Type_Kinds.o Message_Handler.o CRTM_Parameters.o
CRTM_ChannelInfo.o : CRTM_ChannelInfo.f90 Type_Kinds.o Message_Handler.o CRTM_ChannelInfo_Define.o SpcCoeff_Define.o CRTM_SpcCoeff.o

CRTM_Parameters.o : CRTM_Parameters.f90 Type_Kinds.o
CRTM_LifeCycle.o : CRTM_LifeCycle.f90 Message_Handler.o CRTM_SpcCoeff.o CRTM_TauCoeff.o CRTM_AerosolCoeff.o CRTM_CloudCoeff.o CRTM_EmisCoeff.o CRTM_ChannelInfo.o

$(EXE_FILE).o : $(EXE_FILE).f90 Type_Kinds.o Message_Handler.o CRTM_ChannelInfo_Define.o CRTM_ChannelInfo.o CRTM_LifeCycle.o


# -------------------------------
# Create tarball for distribution
# -------------------------------

TAR_FILE = $(EXE_FILE)_software.tar

DATA_ENDIAN_TAGS = Big_Endian

tar:
	$(TARBALL_CREATE) $(TAR_FILE) ${OBJ_FILES:.o=.f90}
	@$(COPY) makefile.dist makefile
	$(TARBALL_APPEND) $(TAR_FILE) makefile
	@$(REMOVE) makefile
	@$(COPY) $(F90_DIR)/make.macros .
	@$(COPY) $(F90_DIR)/make.rules .
	$(TARBALL_APPEND) $(TAR_FILE) make.macros make.rules
	@$(REMOVE) make.macros make.rules
	$(TARBALL_APPEND) $(TAR_FILE) *.bin.$(DATA_ENDIAN_TAGS)
	$(TARBALL_APPEND) $(TAR_FILE) run_Test_Initialization
	compress $(TAR_FILE)



#-----------------------------------------------------------------------------
#                          -- Define default rules --
#-----------------------------------------------------------------------------

include make.rules

