#!/bin/sh

SENSOR_LIST="amsua_n17 airs281SUBSET_aqua hirs3_n17 ssmis_f16"

for SENSOR in ${SENSOR_LIST}; do
  echo; echo; echo
  echo "======================================="
  echo "Running Test_Initialization for sensor: ${SENSOR}..."
  echo "======================================="
  Test_Initialization -Wl,-T << EOF
${SENSOR}.SpcCoeff.bin.Big_Endian
${SENSOR}.TauCoeff.bin.Big_Endian
CloudCoeff.bin.Big_Endian
AerosolCoeff.bin.Big_Endian
EmisCoeff.bin.Big_Endian
EOF

done
