#!/bin/sh

endian_dir=$1
if [ "${endian_dir}" != "Big_Endian" ] && [ "${endian_dir}" != "Little_Endian" ]; then
  echo "Invalid endian directory: >${endian_dir}<"
  exit 1
fi
  

root_dir="${CRTM_FIXFILE_ROOT}/EmisCoeff"
emis_types="IR_Land IR_Snow IR_Ice VIS_Snow VIS_Ice VIS_Water VIS_Land"
format_dir="SEcategory"

for emis_dir in ${emis_types}; do
  case ${emis_dir} in
    "IR_Land") emis_id="IRland";;
    "IR_Snow") emis_id="IRsnow";;
    "IR_Ice") emis_id="IRice";;
    "VIS_Snow") emis_id="VISsnow";;
    "VIS_Ice") emis_id="VISice";;
    "VIS_Water") emis_id="VISwater";;
    "VIS_Land") emis_id="VISland";;
  esac
  dest="${root_dir}/${emis_dir}/${format_dir}/${endian_dir}"
  if [ ! -d ${dest} ]; then
    echo "${dest} directory does not exist!"
    exit 1
  fi
  mv *.${emis_id}.EmisCoeff.bin ${root_dir}/${emis_dir}/${format_dir}/${endian_dir}
done
