!
! AMSRE_EmisCoeff_Binary_IO
!
! Module containing routines to read and write Binary format
! AMSRE_EmisCoeff data files.
!
! CREATION HISTORY:
!       This file was automatically generated so edit at your own risk.
!       Generated by header.rb on 18-Mar-2007
!       Contact info:  Paul van Delst, CIMSS/SSEC
!                      paul.vandelst@ssec.wisc.edu
!

MODULE AMSRE_EmisCoeff_Binary_IO

  ! ------------------
  ! Environment set up
  ! ------------------
  ! Module use
  USE Type_Kinds           , ONLY: fp
  USE File_Utility         , ONLY: Get_Lun
  USE Binary_File_Utility  , ONLY: Open_Binary_File
  USE Message_Handler      , ONLY: SUCCESS, FAILURE, INFORMATION, Display_Message
  USE Compare_Float_Numbers, ONLY: Compare_Float
  USE AMSRE_EmisCoeff_Define
  ! Disable implicit typing
  IMPLICIT NONE


  ! ------------
  ! Visibilities
  ! ------------
  ! Everything private by default
  PRIVATE
  ! Structure procedures
  PUBLIC :: Inquire_AMSRE_EmisCoeff_Binary
  PUBLIC :: Read_AMSRE_EmisCoeff_Binary
  PUBLIC :: Write_AMSRE_EmisCoeff_Binary
    

  ! -----------------
  ! Module parameters
  ! -----------------
  ! RCS Id for the module
  CHARACTER(*), PARAMETER :: MODULE_RCS_ID = &
  '$Id: $'
  ! Keyword set value
  INTEGER, PARAMETER :: SET = 1


CONTAINS
  FUNCTION Inquire_AMSRE_EmisCoeff_Binary( &
             Filename     , &  ! Input
             n_Wind_Speeds, &  ! Optional Output
             n_Frequencies, &  ! Optional Output
             Release      , &  ! Optional Output
             Version      , &  ! Optional Output
             RCS_Id       , &  ! Revision Control
             Message_Log  ) &  ! Error Messaging
           RESULT( Error_Status )
    ! Arguments
    CHARACTER(*)          , INTENT(IN)  :: Filename
    INTEGER     , OPTIONAL, INTENT(OUT) :: n_Wind_Speeds
    INTEGER     , OPTIONAL, INTENT(OUT) :: n_Frequencies
    INTEGER     , OPTIONAL, INTENT(OUT) :: Release
    INTEGER     , OPTIONAL, INTENT(OUT) :: Version
    CHARACTER(*), OPTIONAL, INTENT(OUT) :: RCS_Id
    CHARACTER(*), OPTIONAL, INTENT(IN)  :: Message_Log
    ! Function result
    INTEGER :: Error_Status
    ! Local parameters
    CHARACTER(*), PARAMETER :: ROUTINE_NAME = 'Inquire_AMSRE_EmisCoeff_Binary'
    ! Local variables
    CHARACTER(256) :: Message
    INTEGER :: IO_Status
    INTEGER :: FileID
    INTEGER :: Rel, Ver
    INTEGER :: i1,i2

    ! Set up
    Error_Status = SUCCESS
    IF ( PRESENT( RCS_Id ) ) RCS_Id = MODULE_RCS_ID

    ! Open the Binary format AMSRE_EmisCoeff file
    Error_Status = Open_Binary_File( TRIM(Filename), &
                                     FileID, &
                                     Message_Log=Message_Log)
    IF ( Error_Status /= SUCCESS ) THEN
      Error_Status = FAILURE
      CALL Display_Message( &
             ROUTINE_NAME, &
             'Error opening AMSRE_EmisCoeff file '//TRIM(Filename), &
             Error_Status, &
             Message_Log=Message_Log )
      RETURN
    END IF

    ! Read the Release and Version information
    READ(FileID, IOSTAT=IO_Status) Rel, Ver
    IF ( IO_Status /= 0 ) THEN
      WRITE(Message,'("Error reading AMSRE_EmisCoeff Release/Version values from ", a, &
                     &". IOSTAT = ", i0 )' ) &
                     TRIM(Filename), IO_Status
      CLOSE(FileID)
      Error_Status = FAILURE
      CALL Display_Message( &
             ROUTINE_NAME, &
             TRIM(Message), &
             Error_Status, &
             Message_Log=Message_Log )
      RETURN
    END IF

    ! Read the data dimensions
    READ(FileID, IOSTAT=IO_Status) i1, i2
    IF ( IO_Status /= 0 ) THEN
      WRITE(Message,'("Error reading AMSRE_EmisCoeff dimension values from ", a, &
                     &". IOSTAT = ", i0 )' ) &
                     TRIM(Filename), IO_Status
      CLOSE(FileID)
      Error_Status = FAILURE
      CALL Display_Message( &
             ROUTINE_NAME, &
             TRIM(Message), &
             Error_Status, &
             Message_Log=Message_Log )
      RETURN
    END IF

    ! Assign the return arguments
    !
    ! Dimensions
    IF ( PRESENT(n_Wind_Speeds) ) THEN
      n_Wind_Speeds = i1
    END IF
    IF ( PRESENT(n_Frequencies) ) THEN
      n_Frequencies = i2
    END IF
    ! Release/Version information
    IF ( PRESENT(Release) ) THEN
      Release = Rel
    END IF
    IF ( PRESENT(Version) ) THEN
      Version = Ver
    END IF

    ! Close the file
    CLOSE( FileID, STATUS='KEEP', &
           IOSTAT = IO_Status )
    IF ( IO_Status /= 0 ) THEN
      WRITE(Message,'("Error closing ", a, ". IOSTAT = ", i0 )' ) &
                    TRIM(Filename), IO_Status
      Error_Status = FAILURE
      CALL Display_Message( &
             ROUTINE_NAME, &
             TRIM(Message), &
             Error_Status, &
             Message_Log=Message_Log )
      RETURN
    END IF
    
  END FUNCTION Inquire_AMSRE_EmisCoeff_Binary
  FUNCTION Read_AMSRE_EmisCoeff_Binary( &
             Filename       , &  ! Input
             AMSRE_EmisCoeff, &  ! Output
             Quiet          , &  ! Optional Input
             RCS_Id         , &  ! Revision Control
             Message_Log    ) &  ! Error Messaging
           RESULT( Error_Status )
    ! Arguments
    CHARACTER(*)              , INTENT(IN)     :: Filename
    TYPE(AMSRE_EmisCoeff_type), INTENT(IN OUT) :: AMSRE_EmisCoeff
    INTEGER     , OPTIONAL    , INTENT(IN)     :: Quiet
    CHARACTER(*), OPTIONAL    , INTENT(OUT)    :: RCS_Id
    CHARACTER(*), OPTIONAL    , INTENT(IN)     :: Message_Log
    ! Function result
    INTEGER :: Error_Status
    ! Local parameters
    CHARACTER(*), PARAMETER :: ROUTINE_NAME = 'Read_AMSRE_EmisCoeff_Binary'
    ! Local variables
    CHARACTER(256) :: Message
    LOGICAL :: Noisy
    INTEGER :: IO_Status
    INTEGER :: FileID
    INTEGER :: Scalar_IO_Status(1)
    INTEGER :: Array_IO_Status(3)
    INTEGER :: i
    INTEGER :: i1, i2

    ! Set up
    Error_Status = SUCCESS
    IF ( PRESENT( RCS_Id ) ) RCS_Id = MODULE_RCS_ID

    ! Output informational messages...
    Noisy = .TRUE.
    ! ...unless the Quiet keyword is set
    IF ( PRESENT(Quiet) ) THEN
      IF ( Quiet == SET ) Noisy = .FALSE.
    END IF
    
    ! Open the Binary format AMSRE_EmisCoeff file
    Error_Status = Open_Binary_File( TRIM(Filename), &
                                     FileID, &
                                     Message_Log=Message_Log)
    IF ( Error_Status /= SUCCESS ) THEN
      Error_Status = FAILURE
      CALL Display_Message( &
             ROUTINE_NAME, &
             'Error opening AMSRE_EmisCoeff file '//TRIM(Filename), &
             Error_Status, &
             Message_Log=Message_Log )
      RETURN
    END IF

    ! Read the Release and Version information
    READ(FileID, IOSTAT=IO_Status) AMSRE_EmisCoeff%Release, AMSRE_EmisCoeff%Version
    IF ( IO_Status /= 0 ) THEN
      WRITE(Message,'("Error reading AMSRE_EmisCoeff Release/Version values from ", a, &
                     &". IOSTAT = ", i0 )' ) &
                     TRIM(Filename), IO_Status
      CLOSE(FileID)
      Error_Status = FAILURE
      CALL Display_Message( &
             ROUTINE_NAME, &
             TRIM(Message), &
             Error_Status, &
             Message_Log=Message_Log )
      RETURN
    END IF

    ! Check the release
    Error_Status = CheckRelease_AMSRE_EmisCoeff( &
                     AMSRE_EmisCoeff, &
                     Message_Log=Message_Log)
    IF ( Error_Status /= SUCCESS ) THEN
      CLOSE(FileID)
      Error_Status = FAILURE
      CALL Display_Message( &
             ROUTINE_NAME, &
             'AMSRE_EmisCoeff Release check failed for '//TRIM(Filename), &
             Error_Status, &
             Message_Log=Message_Log )
      RETURN
    END IF


    ! Read the data dimensions
    READ(FileID, IOSTAT=IO_Status) i1, i2
    IF ( IO_Status /= 0 ) THEN
      WRITE(Message,'("Error reading AMSRE_EmisCoeff dimension values from ", a, &
                     &". IOSTAT = ", i0 )' ) &
                     TRIM(Filename), IO_Status
      CLOSE(FileID)
      Error_Status = FAILURE
      CALL Display_Message( &
             ROUTINE_NAME, &
             TRIM(Message), &
             Error_Status, &
             Message_Log=Message_Log )
      RETURN
    END IF

    ! Allocate the structure            
    Error_Status = Allocate_AMSRE_EmisCoeff( i1, &
                                             i2, &
                                             AMSRE_EmisCoeff, &
                                             Message_Log=Message_Log )
    IF ( Error_Status /= SUCCESS ) THEN
      CLOSE(FileID)
      Error_Status = FAILURE
      CALL Display_Message( &
             ROUTINE_NAME, &
             'Error allocating AMSRE_EmisCoeff structure', &
             Error_Status, &
             Message_Log=Message_Log )
      RETURN
    END IF
    
    ! Read the scalar data items
    READ(FileID, IOSTAT=Scalar_IO_Status(1)) AMSRE_EmisCoeff%Sensor_Id
    IF ( ANY( Scalar_IO_Status /= 0 ) ) THEN
      WRITE(Message,'("Error reading AMSRE_EmisCoeff scalar variable(s) ",1(1x,i0,:))') &
                    PACK( (/(i,i=1,1)/), &
                          Scalar_IO_Status /= 0 )
      CLOSE(FileID)
      Error_Status = FAILURE
      CALL Display_Message( &
             ROUTINE_NAME, &
             TRIM(Message), &
             Error_Status, &
             Message_Log=Message_Log )
      RETURN
    END IF

    ! Read the array data items
    READ(FileID, IOSTAT=Array_IO_Status(1)) AMSRE_EmisCoeff%Wind_Speed
    READ(FileID, IOSTAT=Array_IO_Status(2)) AMSRE_EmisCoeff%Frequency
    READ(FileID, IOSTAT=Array_IO_Status(3)) AMSRE_EmisCoeff%sdd
    IF ( ANY( Array_IO_Status /= 0 ) ) THEN
      WRITE(Message,'("Error reading AMSRE_EmisCoeff array variable(s) ",3(1x,i0,:))') &
                    PACK( (/(i,i=1,3)/), &
                          Array_IO_Status /= 0 )
      CLOSE(FileID)
      Error_Status = FAILURE
      CALL Display_Message( &
             ROUTINE_NAME, &
             TRIM(Message), &
             Error_Status, &
             Message_Log=Message_Log )
      RETURN
    END IF

    ! Close the file
    CLOSE( FileID, STATUS='KEEP', &
           IOSTAT = IO_Status )
    IF ( IO_Status /= 0 ) THEN
      WRITE(Message,'("Error closing ", a, ". IOSTAT = ", i0 )' ) &
                    TRIM(Filename), IO_Status
      Error_Status = FAILURE
      CALL Display_Message( &
             ROUTINE_NAME, &
             TRIM(Message), &
             Error_Status, &
             Message_Log=Message_Log )
      RETURN
    END IF
    
    ! Output an info message
    IF ( Noisy ) THEN
      CALL Info_AMSRE_EmisCoeff( AMSRE_EmisCoeff, Message )
      CALL Display_Message( ROUTINE_NAME, &
                            'FILE: '//TRIM(Filename)//'; '//TRIM(Message), &
                            INFORMATION, &
                            Message_Log=Message_Log )
    END IF

  END FUNCTION Read_AMSRE_EmisCoeff_Binary


  FUNCTION Write_AMSRE_EmisCoeff_Binary( &
             Filename       , &  ! Input
             AMSRE_EmisCoeff, &  ! Output
             Quiet          , &  ! Optional Input
             RCS_Id         , &  ! Revision Control
             Message_Log    ) &  ! Error Messaging
           RESULT( Error_Status )
    ! Arguments
    CHARACTER(*)              , INTENT(IN)  :: Filename
    TYPE(AMSRE_EmisCoeff_type), INTENT(IN)  :: AMSRE_EmisCoeff
    INTEGER     , OPTIONAL    , INTENT(IN)  :: Quiet
    CHARACTER(*), OPTIONAL    , INTENT(OUT) :: RCS_Id
    CHARACTER(*), OPTIONAL    , INTENT(IN)  :: Message_Log
    ! Function result
    INTEGER :: Error_Status
    ! Local parameters
    CHARACTER(*), PARAMETER :: ROUTINE_NAME = 'Write_AMSRE_EmisCoeff_Binary'
    CHARACTER(*), PARAMETER :: FILE_STATUS_ON_ERROR = 'DELETE'
    ! Local variables
    CHARACTER(256) :: Message
    LOGICAL :: Noisy
    INTEGER :: IO_Status
    INTEGER :: FileID
    INTEGER :: Scalar_IO_Status(1)
    INTEGER :: Array_IO_Status(3)
    INTEGER :: i

    ! Set up
    Error_Status = SUCCESS
    IF ( PRESENT( RCS_Id ) ) RCS_Id = MODULE_RCS_ID

    ! Output informational messages...
    Noisy = .TRUE.
    ! ...unless the Quiet keyword is set
    IF ( PRESENT(Quiet) ) THEN
      IF ( Quiet == SET ) Noisy = .FALSE.
    END IF

    ! Check structure association status
    IF ( .NOT. Associated_AMSRE_EmisCoeff( AMSRE_EmisCoeff ) ) THEN
      Error_Status = FAILURE
      CALL Display_Message( &
             ROUTINE_NAME, &
             'Some or all INPUT AMSRE_EmisCoeff pointer members are NOT associated.', &
             Error_Status, &
             Message_Log=Message_Log )
      RETURN
    END IF
    
    ! Check the release
    Error_Status = CheckRelease_AMSRE_EmisCoeff( &
                     AMSRE_EmisCoeff, &
                     Message_Log=Message_Log)
    IF ( Error_Status /= SUCCESS ) THEN
      CLOSE(FileID)
      Error_Status = FAILURE
      CALL Display_Message( &
             ROUTINE_NAME, &
             'AMSRE_EmisCoeff Release check failed for '//TRIM(Filename), &
             Error_Status, &
             Message_Log=Message_Log )
      RETURN
    END IF


    ! Check the dimensions
    IF (AMSRE_EmisCoeff%n_Wind_Speeds < 1 .OR. &
        AMSRE_EmisCoeff%n_Frequencies < 1) THEN
      Error_Status = FAILURE
      CALL Display_Message( &
             ROUTINE_NAME, &
             'Input AMSRE_EmisCoeff dimensions must all be > 0.', &
             Error_Status, &
             Message_Log=Message_Log )
      RETURN
    END IF

    ! Open the Binary format AMSRE_EmisCoeff file
    Error_Status = Open_Binary_File( TRIM(Filename), &
                                     FileID, &
                                     For_Output =SET, &
                                     Message_Log=Message_Log)
    IF ( Error_Status /= SUCCESS ) THEN
      Error_Status = FAILURE
      CALL Display_Message( &
             ROUTINE_NAME, &
             'Error opening AMSRE_EmisCoeff file '//TRIM(Filename), &
             Error_Status, &
             Message_Log=Message_Log )
      RETURN
    END IF

    ! Write the Release and Version information
    WRITE(FileID, IOSTAT=IO_Status) AMSRE_EmisCoeff%Release, AMSRE_EmisCoeff%Version
    IF ( IO_Status /= 0 ) THEN
      WRITE(Message,'("Error writing AMSRE_EmisCoeff Release/Version values to ", a, &
                     &". IOSTAT = ", i0 )' ) &
                     TRIM(Filename), IO_Status
      CLOSE(FileID)
      Error_Status = FAILURE
      CALL Display_Message( &
             ROUTINE_NAME, &
             TRIM(Message), &
             Error_Status, &
             Message_Log=Message_Log )
      RETURN
    END IF
    
    ! Write the data dimensions
    WRITE(FileID, IOSTAT=IO_Status) &
      AMSRE_EmisCoeff%n_Wind_Speeds, AMSRE_EmisCoeff%n_Frequencies
    IF ( IO_Status /= 0 ) THEN
      WRITE(Message,'("Error writing AMSRE_EmisCoeff dimension values to ", a, &
                     &". IOSTAT = ", i0 )' ) &
                     TRIM(Filename), IO_Status
      CLOSE(FileID)
      Error_Status = FAILURE
      CALL Display_Message( &
             ROUTINE_NAME, &
             TRIM(Message), &
             Error_Status, &
             Message_Log=Message_Log )
      RETURN
    END IF

    ! Write the scalar data items
    WRITE(FileID, IOSTAT=Scalar_IO_Status(1)) AMSRE_EmisCoeff%Sensor_Id
    IF ( ANY( Scalar_IO_Status /= 0 ) ) THEN
      WRITE(Message,'("Error writing AMSRE_EmisCoeff scalar variable(s) ",1(1x,i0,:))') &
                    PACK( (/(i,i=1,1)/), &
                          Scalar_IO_Status /= 0 )
      CLOSE(FileID)
      Error_Status = FAILURE
      CALL Display_Message( &
             ROUTINE_NAME, &
             TRIM(Message), &
             Error_Status, &
             Message_Log=Message_Log )
      RETURN
    END IF

    ! Write the array data items
    WRITE(FileID, IOSTAT=Array_IO_Status(1)) AMSRE_EmisCoeff%Wind_Speed
    WRITE(FileID, IOSTAT=Array_IO_Status(2)) AMSRE_EmisCoeff%Frequency
    WRITE(FileID, IOSTAT=Array_IO_Status(3)) AMSRE_EmisCoeff%sdd
    IF ( ANY( Array_IO_Status /= 0 ) ) THEN
      WRITE(Message,'("Error writing AMSRE_EmisCoeff array variable(s) ",3(1x,i0,:))') &
                    PACK( (/(i,i=1,3)/), &
                          Array_IO_Status /= 0 )
      CLOSE(FileID)
      Error_Status = FAILURE
      CALL Display_Message( &
             ROUTINE_NAME, &
             TRIM(Message), &
             Error_Status, &
             Message_Log=Message_Log )
      RETURN
    END IF

    ! Close the file
    CLOSE( FileID, STATUS='KEEP', &
           IOSTAT = IO_Status )
    IF ( IO_Status /= 0 ) THEN
      WRITE(Message,'("Error closing ", a, ". IOSTAT = ", i0 )' ) &
                    TRIM(Filename), IO_Status
      Error_Status = FAILURE
      CALL Display_Message( &
             ROUTINE_NAME, &
             TRIM(Message), &
             Error_Status, &
             Message_Log=Message_Log )
      RETURN
    END IF
    
    ! Output an info message
    IF ( Noisy ) THEN
      CALL Info_AMSRE_EmisCoeff( AMSRE_EmisCoeff, Message )
      CALL Display_Message( ROUTINE_NAME, &
                            'FILE: '//TRIM(Filename)//'; '//TRIM(Message), &
                            INFORMATION, &
                            Message_Log=Message_Log )
    END IF

  END FUNCTION Write_AMSRE_EmisCoeff_Binary

END MODULE AMSRE_EmisCoeff_Binary_IO
