!
! AMSRE_EmisCoeff_Define
!
! Module defining the AMSRE_EmisCoeff data structure and containing routines to 
! manipulate it.
!
! CREATION HISTORY:
!       This file was automatically generated so edit at your own risk.
!       Generated by header.rb on 18-Mar-2007
!       Contact info:  Paul van Delst, CIMSS/SSEC
!                      paul.vandelst@ssec.wisc.edu
!

MODULE AMSRE_EmisCoeff_Define

  ! ------------------
  ! Environment set up
  ! ------------------
  ! Module use
  USE Type_Kinds           , ONLY: fp
  USE Message_Handler      , ONLY: SUCCESS, FAILURE, Display_Message
  USE Compare_Float_Numbers, ONLY: Compare_Float
  ! Disable implicit typing
  IMPLICIT NONE


  ! ------------
  ! Visibilities
  ! ------------
  ! Everything private by default
  PRIVATE
  ! Data structure definition
  PUBLIC :: AMSRE_EmisCoeff_type
  ! Structure procedures
  PUBLIC :: Associated_AMSRE_EmisCoeff
  PUBLIC :: Destroy_AMSRE_EmisCoeff
  PUBLIC :: Allocate_AMSRE_EmisCoeff
  PUBLIC :: Assign_AMSRE_EmisCoeff
  PUBLIC :: Equal_AMSRE_EmisCoeff
  PUBLIC :: Info_AMSRE_EmisCoeff
  PUBLIC :: CheckRelease_AMSRE_EmisCoeff
    

  ! -----------------
  ! Module parameters
  ! -----------------
  ! RCS Id for the module
  CHARACTER(*), PARAMETER :: MODULE_RCS_ID = &
  '$Id: $'
  ! Literal constants
  REAL(fp), PARAMETER :: ZERO = 0.0_fp
  ! String length
  INTEGER, PARAMETER :: SL = 20
  ! Current valid release and version numbers
  INTEGER, PARAMETER :: AMSRE_EMISCOEFF_RELEASE = 1
  INTEGER, PARAMETER :: AMSRE_EMISCOEFF_VERSION = 1

  ! -----------------------
  ! Derived type definition
  ! -----------------------
  TYPE :: AMSRE_EmisCoeff_type
    INTEGER :: n_Allocates=0
    ! Release and version information
    INTEGER :: Release = AMSRE_EMISCOEFF_RELEASE
    INTEGER :: Version = AMSRE_EMISCOEFF_VERSION
    ! Dimensions
    INTEGER :: n_Wind_Speeds = 0
    INTEGER :: n_Frequencies = 0
    ! Scalars
    CHARACTER(SL) :: Sensor_Id = ' '
    ! Arrays
    REAL(fp), DIMENSION(:)  , POINTER :: Wind_Speed => NULL()
    REAL(fp), DIMENSION(:)  , POINTER :: Frequency  => NULL()
    REAL(fp), DIMENSION(:,:), POINTER :: sdd        => NULL()
  END TYPE AMSRE_EmisCoeff_type

CONTAINS
  SUBROUTINE Clear_AMSRE_EmisCoeff(AMSRE_EmisCoeff)
    TYPE(AMSRE_EmisCoeff_type), INTENT(IN OUT) :: AMSRE_EmisCoeff
    AMSRE_EmisCoeff%Sensor_Id = ' '
  END SUBROUTINE Clear_AMSRE_EmisCoeff
  FUNCTION Associated_AMSRE_EmisCoeff( &
             AMSRE_EmisCoeff, &  ! Input
             ANY_Test       ) &  ! Optional input
           RESULT(Association_Status)
    ! Arguments
    TYPE(AMSRE_EmisCoeff_type), INTENT(IN) :: AMSRE_EmisCoeff
    INTEGER, OPTIONAL         , INTENT(IN) :: ANY_Test
    ! Function result
    LOGICAL :: Association_Status
    ! Local variables
    LOGICAL :: ALL_Test
    
    ! Defineault is to test ALL the pointer members
    ! for a true association status....
    ALL_Test = .TRUE.
    ! ...unless the ANY_Test argument is set.
    IF ( PRESENT( ANY_Test ) ) THEN
      IF ( ANY_Test == 1 ) ALL_Test = .FALSE.
    END IF
    
    ! Test the structure associations    
    Association_Status = .FALSE.
    IF (ALL_Test) THEN
      IF (ASSOCIATED(AMSRE_EmisCoeff%Wind_Speed) .AND. &
          ASSOCIATED(AMSRE_EmisCoeff%Frequency ) .AND. &
          ASSOCIATED(AMSRE_EmisCoeff%sdd       )) THEN
        Association_Status = .TRUE.
      END IF
    ELSE
      IF (ASSOCIATED(AMSRE_EmisCoeff%Wind_Speed) .OR. &
          ASSOCIATED(AMSRE_EmisCoeff%Frequency ) .OR. &
          ASSOCIATED(AMSRE_EmisCoeff%sdd       )) THEN
        Association_Status = .TRUE.
      END IF
    END IF
    
  END FUNCTION Associated_AMSRE_EmisCoeff
  FUNCTION Destroy_AMSRE_EmisCoeff( &
             AMSRE_EmisCoeff, &  ! Output
             No_Clear       , &  ! Optional input
             RCS_Id         , &  ! Revision control
             Message_Log    ) &  ! Error messaging
           RESULT(Error_Status)
    ! Arguments
    TYPE(AMSRE_EmisCoeff_type), INTENT(IN OUT) :: AMSRE_EmisCoeff
    INTEGER,      OPTIONAL    , INTENT(IN)     :: No_Clear
    CHARACTER(*), OPTIONAL    , INTENT(OUT)    :: RCS_Id
    CHARACTER(*), OPTIONAL    , INTENT(IN)     :: Message_Log
    ! Function result
    INTEGER :: Error_Status
    ! Local parameters
    CHARACTER(*), PARAMETER :: ROUTINE_NAME = 'Destroy_AMSRE_EmisCoeff'
    ! Local variables
    CHARACTER(256)  :: Message
    LOGICAL :: Clear
    INTEGER :: Allocate_Status
    
    ! Set up
    Error_Status = SUCCESS
    IF ( PRESENT( RCS_Id ) ) RCS_Id = MODULE_RCS_ID
    
    ! Default is to clear scalar members...
    Clear = .TRUE.
    ! ....unless the No_Clear argument is set
    IF ( PRESENT( No_Clear ) ) THEN
      IF ( No_Clear == 1 ) Clear = .FALSE.
    END IF
    
    ! Initialise the scalar members
    IF ( Clear ) CALL Clear_AMSRE_EmisCoeff(AMSRE_EmisCoeff)
    
    ! If ALL pointer members are NOT associated, do nothing
    IF ( .NOT. Associated_AMSRE_EmisCoeff(AMSRE_EmisCoeff) ) RETURN
    
    ! Deallocate the pointer members
    DEALLOCATE( AMSRE_EmisCoeff%Wind_Speed, &
                AMSRE_EmisCoeff%Frequency, &
                AMSRE_EmisCoeff%sdd, &
                STAT = Allocate_Status )
    IF ( Allocate_Status /= 0 ) THEN
      WRITE( Message, '("Error deallocating AMSRE_EmisCoeff. STAT = ",i0)') &
                      Allocate_Status
      Error_Status = FAILURE
      CALL Display_Message( &
             ROUTINE_NAME, &
             TRIM(Message), &
             Error_Status, &
             Message_Log=Message_Log )
      RETURN
    END IF

    ! Reset the dimension indicators
    AMSRE_EmisCoeff%n_Wind_Speeds = 0
    AMSRE_EmisCoeff%n_Frequencies = 0
    
    ! Decrement and test allocation counter
    AMSRE_EmisCoeff%n_Allocates = AMSRE_EmisCoeff%n_Allocates - 1
    IF ( AMSRE_EmisCoeff%n_Allocates /= 0 ) THEN
      WRITE( Message, '("Allocation counter /= 0, Value = ",i0)') &
                      AMSRE_EmisCoeff%n_Allocates
      Error_Status = FAILURE
      CALL Display_Message( &
             ROUTINE_NAME, &
             TRIM(Message), &
             Error_Status, &
             Message_Log=Message_Log )
      RETURN
    END IF
    
  END FUNCTION Destroy_AMSRE_EmisCoeff
  FUNCTION Allocate_AMSRE_EmisCoeff( &
             n_Wind_Speeds  , &  ! Input
             n_Frequencies  , &  ! Input
             AMSRE_EmisCoeff, &  ! Output
             RCS_Id         , &  ! Revision control
             Message_Log    ) &  ! Error messaging
           RESULT( Error_Status )
    ! Arguments
    INTEGER                   , INTENT(IN) :: n_Wind_Speeds
    INTEGER                   , INTENT(IN) :: n_Frequencies
    TYPE(AMSRE_EmisCoeff_type), INTENT(IN OUT) :: AMSRE_EmisCoeff
    CHARACTER(*), OPTIONAL    , INTENT(OUT)    :: RCS_Id
    CHARACTER(*), OPTIONAL    , INTENT(IN)     :: Message_Log
    ! Function result
    INTEGER :: Error_Status
    ! Local parameters
    CHARACTER(*), PARAMETER :: ROUTINE_NAME = 'Allocate_AMSRE_EmisCoeff'
    ! Local variables
    CHARACTER(256) :: Message
    INTEGER :: Allocate_Status
    
    ! Set up
    Error_Status = SUCCESS
    IF ( PRESENT( RCS_Id ) ) RCS_Id = MODULE_RCS_ID
    
    ! Check dimensions
    IF (n_Wind_Speeds < 1 .OR. &
        n_Frequencies < 1) THEN
      Error_Status = FAILURE
      CALL Display_Message( &
             ROUTINE_NAME, &
             'Input AMSRE_EmisCoeff dimensions must all be > 0.', &
             Error_Status, &
             Message_Log=Message_Log )
      RETURN
    END IF
    
    ! Check if ANY pointers are already associated.
    ! If they are, deallocate them but leave scalars.
    IF ( Associated_AMSRE_EmisCoeff( AMSRE_EmisCoeff, ANY_Test=1 ) ) THEN
      Error_Status = Destroy_AMSRE_EmisCoeff( &
                       AMSRE_EmisCoeff, &
                       No_Clear=1, &
                       Message_Log=Message_Log )
      IF ( Error_Status /= SUCCESS ) THEN
        Error_Status = FAILURE
        CALL Display_Message( &
               ROUTINE_NAME, &
               'Error deallocating AMSRE_EmisCoeff prior to allocation.', &
               Error_Status, &
               Message_Log=Message_Log )
        RETURN
      END IF
    END IF
    
    ! Perform the pointer allocation
    ALLOCATE( AMSRE_EmisCoeff%Wind_Speed(1:n_Wind_Speeds), &
              AMSRE_EmisCoeff%Frequency(1:n_Frequencies), &
              AMSRE_EmisCoeff%sdd(1:n_Wind_Speeds,1:n_Frequencies), &
              STAT = Allocate_Status )
    IF ( Allocate_Status /= 0 ) THEN
      WRITE(Message,'("Error allocating AMSRE_EmisCoeff data arrays. STAT = ",i0)') &
                    Allocate_Status
      Error_Status = FAILURE
      CALL Display_Message( &
             ROUTINE_NAME, &
             TRIM(Message), &
             Error_Status, &
             Message_Log=Message_Log )
      RETURN
    END IF
    
    ! Assign the dimensions
    AMSRE_EmisCoeff%n_Wind_Speeds = n_Wind_Speeds
    AMSRE_EmisCoeff%n_Frequencies = n_Frequencies
    
    ! Initialise the arrays
    AMSRE_EmisCoeff%Wind_Speed = ZERO
    AMSRE_EmisCoeff%Frequency  = ZERO
    AMSRE_EmisCoeff%sdd        = ZERO
    
    ! Increment and test the allocation counter
    AMSRE_EmisCoeff%n_Allocates = AMSRE_EmisCoeff%n_Allocates + 1
    IF ( AMSRE_EmisCoeff%n_Allocates /= 1 ) THEN
      WRITE( Message, '("Allocation counter /= 1, Value = ",i0)') &
                      AMSRE_EmisCoeff%n_Allocates
      Error_Status = FAILURE
      CALL Display_Message( &
             ROUTINE_NAME, &
             TRIM(Message), &
             Error_Status, &
             Message_Log=Message_Log )
      RETURN
    END IF
    
  END FUNCTION Allocate_AMSRE_EmisCoeff
  FUNCTION Assign_AMSRE_EmisCoeff( &
             AMSRE_EmisCoeff_in , &  ! Input
             AMSRE_EmisCoeff_out, &  ! Output
             RCS_Id             , &  ! Revision control
             Message_Log        ) &  ! Error messaging
           RESULT( Error_Status )
    ! Arguments
    TYPE(AMSRE_EmisCoeff_type), INTENT(IN)     :: AMSRE_EmisCoeff_in
    TYPE(AMSRE_EmisCoeff_type), INTENT(IN OUT) :: AMSRE_EmisCoeff_out
    CHARACTER(*), OPTIONAL    , INTENT(OUT)    :: RCS_Id
    CHARACTER(*), OPTIONAL    , INTENT(IN)     :: Message_Log
    ! Function result
    INTEGER :: Error_Status
    ! Local parameters
    CHARACTER(*), PARAMETER :: ROUTINE_NAME = 'Assign_AMSRE_EmisCoeff'
    ! Local variables
    INTEGER :: i1,i2

    ! Set up
    Error_Status = SUCCESS
    IF ( PRESENT( RCS_Id ) ) RCS_Id = MODULE_RCS_ID

    ! ALL *input* pointers must be associated
    IF ( .NOT. Associated_AMSRE_EmisCoeff( AMSRE_EmisCoeff_in ) ) THEN
      Error_Status = FAILURE
      CALL Display_Message( &
             ROUTINE_NAME, &
             'Some or all INPUT AMSRE_EmisCoeff_in pointer members are NOT associated.', &
             Error_Status, &
             Message_Log=Message_Log )
      RETURN
    END IF
    
    ! Allocate data arrays
    Error_Status = Allocate_AMSRE_EmisCoeff( AMSRE_EmisCoeff_in%n_Wind_Speeds, &
                                             AMSRE_EmisCoeff_in%n_Frequencies, &
                                             AMSRE_EmisCoeff_out, &
                                             Message_Log=Message_Log )
    IF ( Error_Status /= SUCCESS ) THEN
      Error_Status = FAILURE
      CALL Display_Message( &
             ROUTINE_NAME, &
             'Error allocating output structure', &
             Error_Status, &
             Message_Log=Message_Log )
      RETURN
    END IF
    
    ! Assign non-dimension scalar members
    AMSRE_EmisCoeff_out%Sensor_Id = AMSRE_EmisCoeff_in%Sensor_Id
    
    ! Copy array data
    AMSRE_EmisCoeff_out%Wind_Speed = AMSRE_EmisCoeff_in%Wind_Speed
    AMSRE_EmisCoeff_out%Frequency  = AMSRE_EmisCoeff_in%Frequency
    AMSRE_EmisCoeff_out%sdd        = AMSRE_EmisCoeff_in%sdd
    
  END FUNCTION Assign_AMSRE_EmisCoeff
  FUNCTION Equal_AMSRE_EmisCoeff( &
             AMSRE_EmisCoeff_LHS, &  ! Input
             AMSRE_EmisCoeff_RHS, &  ! Input
             ULP_Scale          , &  ! Optional input
             RCS_Id             , &  ! Revision control
             Message_Log        ) &  ! Error messaging
           RESULT( Error_Status )
    ! Arguments
    TYPE(AMSRE_EmisCoeff_type), INTENT(IN)  :: AMSRE_EmisCoeff_LHS
    TYPE(AMSRE_EmisCoeff_type), INTENT(IN)  :: AMSRE_EmisCoeff_RHS
    INTEGER,      OPTIONAL    , INTENT(IN)  :: ULP_Scale
    CHARACTER(*), OPTIONAL    , INTENT(OUT) :: RCS_Id
    CHARACTER(*), OPTIONAL    , INTENT(IN)  :: Message_Log
    ! Function result
    INTEGER :: Error_Status
    ! Local parameters
    CHARACTER(*), PARAMETER :: ROUTINE_NAME = 'Equal_AMSRE_EmisCoeff'
    ! Local variables
    CHARACTER(256) :: Message
    INTEGER :: ULP
    INTEGER :: l, j
    INTEGER :: i1,i2

    ! Set up
    Error_Status = SUCCESS
    IF ( PRESENT( RCS_Id ) ) RCS_Id = MODULE_RCS_ID

    ! Default precision is a single unit in last place
    ULP = 1
    ! ... unless the ULP_Scale argument is set and positive
    IF ( PRESENT( ULP_Scale ) ) THEN
      IF ( ULP_Scale > 0 ) ULP = ULP_Scale
    END IF

    ! Check the structure association status
    IF ( .NOT. Associated_AMSRE_EmisCoeff( AMSRE_EmisCoeff_LHS ) ) THEN
      Error_Status = FAILURE
      CALL Display_Message( &
             ROUTINE_NAME, &
             'Some or all INPUT AMSRE_EmisCoeff_LHS pointer members are NOT associated.', &
             Error_Status, &
             Message_Log=Message_Log )
      RETURN
    END IF
    IF ( .NOT. Associated_AMSRE_EmisCoeff( AMSRE_EmisCoeff_RHS ) ) THEN
      Error_Status = FAILURE
      CALL Display_Message( &
             ROUTINE_NAME, &
             'Some or all INPUT AMSRE_EmisCoeff_RHS pointer members are NOT associated.', &
             Error_Status, &
             Message_Log=Message_Log )
      RETURN
    END IF
    
    ! Check dimensions
    IF (AMSRE_EmisCoeff_LHS%n_Wind_Speeds /= AMSRE_EmisCoeff_RHS%n_Wind_Speeds .OR. &
        AMSRE_EmisCoeff_LHS%n_Frequencies /= AMSRE_EmisCoeff_RHS%n_Frequencies) THEN
      Error_Status = FAILURE
      CALL Display_Message( &
             ROUTINE_NAME, &
             'Structure dimensions are different.', &
             Error_Status, &
             Message_Log=Message_Log )
      RETURN
    END IF

    ! Check the scalar components
    IF ( AMSRE_EmisCoeff_LHS%Sensor_Id /= AMSRE_EmisCoeff_RHS%Sensor_Id ) THEN
      Error_Status = FAILURE
      CALL Display_Message( &
             ROUTINE_NAME, &
             'AMSRE_EmisCoeff scalar component Sensor_Id values are different.', &
             Error_Status, &
             Message_Log=Message_Log )
      RETURN
    END IF
    
    ! Check the array components
    DO i1=1,AMSRE_EmisCoeff_LHS%n_Wind_Speeds
      IF ( .NOT. Compare_Float( AMSRE_EmisCoeff_LHS%Wind_Speed(i1), &
                                AMSRE_EmisCoeff_RHS%Wind_Speed(i1), &
                                ULP=ULP ) ) THEN
        WRITE(Message,'("AMSRE_EmisCoeff array component Wind_Speed values ",&
                        &"are different at index (",1(1x,i0),")")') &
                        i1
        Error_Status = FAILURE
        CALL Display_Message( &
               ROUTINE_NAME, &
               TRIM(Message), &
               Error_Status, &
               Message_Log=Message_Log )
        RETURN
      END IF
    END DO
    DO i1=1,AMSRE_EmisCoeff_LHS%n_Frequencies
      IF ( .NOT. Compare_Float( AMSRE_EmisCoeff_LHS%Frequency(i1), &
                                AMSRE_EmisCoeff_RHS%Frequency(i1), &
                                ULP=ULP ) ) THEN
        WRITE(Message,'("AMSRE_EmisCoeff array component Frequency values ",&
                        &"are different at index (",1(1x,i0),")")') &
                        i1
        Error_Status = FAILURE
        CALL Display_Message( &
               ROUTINE_NAME, &
               TRIM(Message), &
               Error_Status, &
               Message_Log=Message_Log )
        RETURN
      END IF
    END DO
    DO i2=1,AMSRE_EmisCoeff_LHS%n_Frequencies
      DO i1=1,AMSRE_EmisCoeff_LHS%n_Wind_Speeds
        IF ( .NOT. Compare_Float( AMSRE_EmisCoeff_LHS%sdd(i1,i2), &
                                  AMSRE_EmisCoeff_RHS%sdd(i1,i2), &
                                  ULP=ULP ) ) THEN
          WRITE(Message,'("AMSRE_EmisCoeff array component sdd values ",&
                          &"are different at index (",2(1x,i0),")")') &
                          i1,i2
          Error_Status = FAILURE
          CALL Display_Message( &
                 ROUTINE_NAME, &
                 TRIM(Message), &
                 Error_Status, &
                 Message_Log=Message_Log )
          RETURN
        END IF
      END DO
    END DO
    
  END FUNCTION Equal_AMSRE_EmisCoeff
  SUBROUTINE Info_AMSRE_EmisCoeff( &
               AMSRE_EmisCoeff, &  ! Input
               Info           , &  ! Output
               RCS_Id           )  ! Revision control
    ! Arguments
    TYPE(AMSRE_EmisCoeff_type), INTENT(IN)  :: AMSRE_EmisCoeff
    CHARACTER(*)              , INTENT(OUT) :: Info
    CHARACTER(*), OPTIONAL    , INTENT(OUT) :: RCS_Id
    ! Parameters
    INTEGER, PARAMETER :: CARRIAGE_RETURN = 13
    INTEGER, PARAMETER :: LINEFEED = 10
    ! Local variables
    CHARACTER(80)  :: FmtString
    CHARACTER(512) :: LongString

    ! Set up
    IF ( PRESENT( RCS_Id ) ) RCS_Id = MODULE_RCS_ID

    ! Write the required info to the local string
    FmtString='(a,1x,"AMSRE_EmisCoeff:",2x,&
               &"N_WIND_SPEEDS=",i0,2x,&
               &"N_FREQUENCIES=",i0,2x)'
    WRITE(LongString, FMT=FmtString) &
          ACHAR(CARRIAGE_RETURN)//ACHAR(LINEFEED), &
          AMSRE_EmisCoeff%n_Wind_Speeds, &
          AMSRE_EmisCoeff%n_Frequencies

    ! Trim the output based on the
    ! dummy argument string length
    Info = LongString(1:MIN( LEN(Info), LEN_TRIM(LongString) ))

  END SUBROUTINE Info_AMSRE_EmisCoeff
  FUNCTION CheckRelease_AMSRE_EmisCoeff( &
             AMSRE_EmisCoeff, &  ! Input
             RCS_Id         , &  ! Revision control
             Message_Log    ) &  ! Error messaging
           RESULT( Error_Status )
    ! Arguments
    TYPE(AMSRE_EmisCoeff_type), INTENT(IN)  :: AMSRE_EmisCoeff
    CHARACTER(*), OPTIONAL    , INTENT(OUT) :: RCS_Id
    CHARACTER(*), OPTIONAL    , INTENT(IN)  :: Message_Log
    ! Function result
    INTEGER :: Error_Status
    ! Local parameters
    CHARACTER(*), PARAMETER :: ROUTINE_NAME = 'CheckRelease_AMSRE_EmisCoeff'
    ! Local variables
    CHARACTER(256) :: Message

    ! Set up
    Error_Status = SUCCESS
    IF ( PRESENT( RCS_Id ) ) RCS_Id = MODULE_RCS_ID

    ! Check release is not too old
    IF ( AMSRE_EmisCoeff%Release < AMSRE_EMISCOEFF_RELEASE ) THEN
      WRITE( Message, '( "A AMSRE_EmisCoeff data update is needed. ", &
                        &"AMSRE_EmisCoeff release is ", i0, &
                        &". Valid release is ",i0,"." )' ) &
                      AMSRE_EmisCoeff%Release, AMSRE_EMISCOEFF_RELEASE
      Error_Status = FAILURE
      CALL Display_Message( &
             ROUTINE_NAME, &
             TRIM(Message), &
             Error_Status, &
             Message_Log=Message_Log )
      RETURN
    END IF

    ! Check release is not too new
    IF ( AMSRE_EmisCoeff%Release > AMSRE_EMISCOEFF_RELEASE ) THEN
      WRITE( Message, '( "A AMSRE_EmisCoeff software update is needed. ", &
                        &"AMSRE_EmisCoeff release is ", i0, &
                        &". Valid release is ",i0,"." )' ) &
                      AMSRE_EmisCoeff%Release, AMSRE_EMISCOEFF_RELEASE
      Error_Status = FAILURE
      CALL Display_Message( &
             ROUTINE_NAME, &
             TRIM(Message), &
             Error_Status, &
             Message_Log=Message_Log )
      RETURN
    END IF

  END FUNCTION CheckRelease_AMSRE_EmisCoeff

END MODULE AMSRE_EmisCoeff_Define
