#==============================================================================
#
# Makefile for Planck functions test program
#
#==============================================================================

#-----------------------------------------------------------------------------
#                          -- Define macros --
#-----------------------------------------------------------------------------

include make.macros


# --------------
# This make file
# --------------

MAKE_FILE = makefile


# ---------------
# Executable file
# ---------------

EXE_FILE = Planck_Functions_Test


# ------------
# Object files
# ------------

UTILITY_OBJ_FILES = Type_Kinds.o \
                    File_Utility.o \
                    Error_Handler.o
CONSTANTS_OBJ_FILES = Fundamental_Constants.o
PLANCK_OBJ_FILES = Planck_Functions.o

OBJ_FILES = $(UTILITY_OBJ_FILES) \
            $(CONSTANTS_OBJ_FILES) \
            $(PLANCK_OBJ_FILES) \
            $(EXE_FILE).o



#-----------------------------------------------------------------------------
#                          -- Define dependecies --
#-----------------------------------------------------------------------------

# ---------------------
# Make based on OS type
# ---------------------

all:
	@echo "OS type detected: "`uname -s`
	@case `uname -s` in \
	  "SunOS")    make -f $(MAKE_FILE) test_program $(SUNOS_FLAGS) ;; \
	   "AIX")     make -f $(MAKE_FILE) test_program $(AIX_FLAGS) ;; \
	   "IRIX64" ) make -f $(MAKE_FILE) test_program $(IRIX64_FLAGS) ;; \
	   "Linux" )  make -f $(MAKE_FILE) test_program $(Linux_FLAGS) ;; \
	   *) echo "This system is not supported" ;; \
       esac


# ----------------------
# Make the test programs
# ----------------------

test_program: $(OBJ_FILES)
	$(FL) $(OBJ_FILES) $(FL_FLAGS) $(EXE_FILE)


# --------
# Clean up
# --------

clean:
	$(REMOVE) $(OBJ_FILES) $(EXE_FILE) *.mod *.MOD *.stb


# ---------------
# Dedendency list
# ---------------

Type_Kinds.o : Type_Kinds.f90 
File_Utility.o : File_Utility.f90 
Error_Handler.o : Error_Handler.f90 File_Utility.o 

Fundamental_Constants.o : Fundamental_Constants.f90 Type_Kinds.o 

Planck_Functions.o : Planck_Functions.f90 Type_Kinds.o Fundamental_Constants.o Error_Handler.o 
$(EXE_FILE).o : $(EXE_FILE).f90 Type_Kinds.o Error_Handler.o Planck_Functions.o 


# -------------------------------
# Create tarball for distribution
# -------------------------------

TAR_FILE = $(EXE_FILE)_software.tar

tar:
	$(TARBALL_CREATE) $(TAR_FILE) ${OBJ_FILES:.o=.f90}
	$(TARBALL_APPEND) $(TAR_FILE) makefile
	$(TARBALL_APPEND) $(TAR_FILE) make.macros make.rules
	$(TARBALL_APPEND) $(TAR_FILE) $(EXE_FILE).output
	compress $(TAR_FILE)



#-----------------------------------------------------------------------------
#                          -- Define default rules --
#-----------------------------------------------------------------------------

include make.rules


