#==============================================================================
#
# Makefile for CRTM Adjoint model test program
#
# $Id: Makefile,v 1.10 2006/05/16 14:24:22 wd20pd Exp $
#
#==============================================================================

# Define the executable file
EXE_FILE = Test_Adjoint

# include the common make components
include ../make.common

