#!/bin/sh

PREP=pp
PREFIXES="get put"

for PREFIX in ${PREFIXES}; do

  ${PREP} ${PREFIX}_netCDF_Attribute.rank.ppinput        ${PREFIX}_netCDF_Attribute.rank.ppoutput
  ${PREP} ${PREFIX}_netCDF_Attribute.scalar.ppinput      ${PREFIX}_netCDF_Attribute.scalar.ppoutput
  ${PREP} ${PREFIX}_netCDF_Attribute.scalar_char.ppinput ${PREFIX}_netCDF_Attribute.scalar_char.ppoutput char

  cat ${PREFIX}_netCDF_Attribute.scalar.ppoutput \
      ${PREFIX}_netCDF_Attribute.scalar_char.ppoutput \
      ${PREFIX}_netCDF_Attribute.rank.ppoutput > ${PREFIX}_netCDF_Attribute
  rm ${PREFIX}_netCDF_Attribute.scalar.ppoutput \
     ${PREFIX}_netCDF_Attribute.scalar_char.ppoutput \
     ${PREFIX}_netCDF_Attribute.rank.ppoutput

done


sed '/Insert_Get_netCDF_Attribute/r get_netCDF_Attribute' netCDF_Attribute_Utility.Header_and_Documentation > tmp_file1
sed '/Insert_Get_netCDF_Attribute/d ' tmp_file1 > tmp_file2
rm -f tmp_file1
sed '/Insert_Put_netCDF_Attribute/r put_netCDF_Attribute' tmp_file2 > tmp_file3
rm -f tmp_file2
sed '/Insert_Put_netCDF_Attribute/d ' tmp_file3 > netCDF_Attribute_Utility.f90
rm -f tmp_file3

rm -f get_netCDF_Attribute put_netCDF_Attribute

