  
!--------------------------------------------------------------------------------
! USE list of the oSRF flag check, set, and clear procedures.
!--------------------------------------------------------------------------------
  USE oSRF_Define, ONLY: &
    oSRF_Is_Interpolated, &
    oSRF_Is_Integrated, &
    oSRF_Is_F0_Computed, &
    oSRF_Is_Linearly_Interpolated, &
    oSRF_Is_Gaussian_Integrated, &
    oSRF_Is_Difference, &
    oSRF_Set_Interpolated, &
    oSRF_Set_Integrated, &
    oSRF_Set_F0_Computed, &
    oSRF_Set_Linearly_Interpolated, &
    oSRF_Set_Gaussian_Integrated, &
    oSRF_Set_Difference, &
    oSRF_Clear_Interpolated, &
    oSRF_Clear_Integrated, &
    oSRF_Clear_F0_Computed, &
    oSRF_Clear_Linearly_Interpolated, &
    oSRF_Clear_Gaussian_Integrated, &
    oSRF_Clear_Difference, &
    oSRF_Clear_Flags
