  
!--------------------------------------------------------------------------------
! Visibilities of the oSRF flag check, set, and clear procedures.
!--------------------------------------------------------------------------------
  PUBLIC :: oSRF_Is_Interpolated
  PUBLIC :: oSRF_Is_Integrated
  PUBLIC :: oSRF_Is_F0_Computed
  PUBLIC :: oSRF_Is_Linearly_Interpolated
  PUBLIC :: oSRF_Is_Gaussian_Integrated
  PUBLIC :: oSRF_Is_Difference
  PUBLIC :: oSRF_Set_Interpolated
  PUBLIC :: oSRF_Set_Integrated
  PUBLIC :: oSRF_Set_F0_Computed
  PUBLIC :: oSRF_Set_Linearly_Interpolated
  PUBLIC :: oSRF_Set_Gaussian_Integrated
  PUBLIC :: oSRF_Set_Difference
  PUBLIC :: oSRF_Clear_Interpolated
  PUBLIC :: oSRF_Clear_Integrated
  PUBLIC :: oSRF_Clear_F0_Computed
  PUBLIC :: oSRF_Clear_Linearly_Interpolated
  PUBLIC :: oSRF_Clear_Gaussian_Integrated
  PUBLIC :: oSRF_Clear_Difference
  PUBLIC :: oSRF_Clear_Flags
