  
!--------------------------------------------------------------------------------
! USE list of the oSRF sensor check, set, and clear procedures.
!--------------------------------------------------------------------------------
  USE oSRF_Define, ONLY: &
    oSRF_Is_Microwave_Sensor, &
    oSRF_Is_Infrared_Sensor, &
    oSRF_Is_Visible_Sensor, &
    oSRF_Is_Ultraviolet_Sensor, &
    oSRF_Set_Microwave_Sensor, &
    oSRF_Set_Infrared_Sensor, &
    oSRF_Set_Visible_Sensor, &
    oSRF_Set_Ultraviolet_Sensor, &
    oSRF_Clear_Sensor
