  
!--------------------------------------------------------------------------------
! Visibilities of the oSRF sensor check, set, and clear procedures.
!--------------------------------------------------------------------------------
  PUBLIC :: oSRF_Is_Microwave_Sensor
  PUBLIC :: oSRF_Is_Infrared_Sensor
  PUBLIC :: oSRF_Is_Visible_Sensor
  PUBLIC :: oSRF_Is_Ultraviolet_Sensor
  PUBLIC :: oSRF_Set_Microwave_Sensor
  PUBLIC :: oSRF_Set_Infrared_Sensor
  PUBLIC :: oSRF_Set_Visible_Sensor
  PUBLIC :: oSRF_Set_Ultraviolet_Sensor
  PUBLIC :: oSRF_Clear_Sensor
